import React,{useEffect,useState} from 'react'
import {fetchAdminOverview,fetchReportSummary,requestReportUrl} from '../../services/admin'
import {authHeader} from '../../services/auth'

const statuses=['New','Under Review','Documents Required','In Progress','Completed','Rejected','Cancelled']

export default function ActivityReports(){
 const [data,setData]=useState<any>({activity:[]}),[summary,setSummary]=useState<any>({counts:{}}),[error,setError]=useState('')
 const [filters,setFilters]=useState({status:'',date_from:'',date_to:''})
 useEffect(()=>{fetchAdminOverview().then(setData).catch(()=>setError('Unable to load activity.'));fetchReportSummary().then(setSummary).catch(()=>setError('Unable to load report.'))},[])
 const apply=async()=>{try{setError('');setSummary(await fetchReportSummary(filters))}catch{setError('Unable to apply report filters. Check the selected dates.')}}
 const download=async()=>{try{const r=await fetch(requestReportUrl(filters),{headers:authHeader()});if(!r.ok)throw new Error();const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='request-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setError('Unable to download report.')}}
 const max=Math.max(1,...Object.values(summary.counts||{}).map(Number))
 return <div><div className="section-header"><div><span className="eyebrow">Audit and exports</span><h2>Activity & reports</h2><p>Filter operational results, print a summary, or export the application register.</p></div><div className="button-row"><button className="btn-secondary" onClick={()=>window.print()}>Print report</button><button onClick={download}>Download CSV</button></div></div>{error&&<p className="info" role="alert">{error}</p>}<div className="admin-filters"><label>Status<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>From<input type="date" value={filters.date_from} onChange={e=>setFilters({...filters,date_from:e.target.value})}/></label><label>To<input type="date" value={filters.date_to} onChange={e=>setFilters({...filters,date_to:e.target.value})}/></label><button onClick={apply}>Apply</button></div><div className="dashboard-stat-grid"><div className="dashboard-stat"><span>Filtered requests</span><strong>{summary.total||0}</strong></div><div className="dashboard-stat"><span>Completed fees</span><strong>₹{summary.completed_fee_total||0}</strong></div></div><section className="dashboard-section report-summary"><h3>Status breakdown</h3>{Object.entries(summary.counts||{}).map(([status,count]:any)=><div className="report-row" key={status}><span>{status}</span><div><i style={{width:`${Number(count)/max*100}%`}}/></div><strong>{count}</strong></div>)}</section><div className="dashboard-section"><h3>Recent status activity</h3><ul className="activity-list">{(data.activity||[]).map((a:any)=><li key={a.id}><strong>{a.previous_status||'Created'} → {a.new_status}</strong><small>{a.changed_by} · {a.note||'No note'} · {new Date(a.created_at).toLocaleString()}</small></li>)}</ul></div></div>
}
