import React,{useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {fetchAdminOverview} from '../../services/admin'

export default function AdminDashboard(){
 const [data,setData]=useState<any>({counts:{},activity:[],recent_orders:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{let active=true;fetchAdminOverview().then(r=>{if(active)setData(r)}).catch(()=>{if(active)setError('Unable to load the admin overview. Please refresh and try again.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 const counts=data.counts||{};const active=['New','Under Review','Documents Required','In Progress'].reduce((n,s)=>n+(counts[s]||0),0)
 if(loading)return <div className="dashboard-state"><div className="loading-dot"/><p>Loading admin overview…</p></div>
 return <div className="admin-dashboard"><div className="dashboard-welcome"><div><span className="eyebrow">Operations overview</span><h2>Admin workspace</h2><p>Monitor requests, clients, documents and service delivery.</p></div><Link className="btn btn-primary" to="/admin/orders">Review requests</Link></div>{error&&<p className="info" role="alert">{error}</p>}<div className="dashboard-stat-grid admin-stats"><div className="dashboard-stat"><span>Total requests</span><strong>{data.total_requests||0}</strong><small>All client applications</small></div><div className="dashboard-stat"><span>Active work</span><strong>{active}</strong><small>Needs attention</small></div><div className="dashboard-stat"><span>Completed fees</span><strong>₹{data.completed_fee_total||0}</strong><small>Assistance charges</small></div><div className="dashboard-stat"><span>Open grievances</span><strong>{data.open_grievances||0}</strong><small>Awaiting resolution</small></div><div className="dashboard-stat"><span>Clients</span><strong>{data.client_count||0}</strong><small>Registered accounts</small></div><div className="dashboard-stat"><span>Average rating</span><strong>{data.average_rating||0}/5</strong><small>Client feedback</small></div></div><div className="admin-dashboard-grid"><section className="dashboard-section"><h2>Request pipeline</h2><div className="pipeline-list">{['New','Under Review','Documents Required','In Progress','Completed','Rejected','Cancelled'].map(label=><Link className="pipeline-row" key={label} to={`/admin/orders?status=${encodeURIComponent(label)}`}><span className="pipeline-label"><strong>{label}</strong></span><span className="pipeline-count">{counts[label]||0}</span></Link>)}</div></section><section className="dashboard-section"><h2>Recent activity</h2>{!data.activity?.length?<p>No activity yet.</p>:<ul className="activity-list">{data.activity.slice(0,8).map((a:any)=><li key={a.id}><strong>{a.previous_status||'Created'} → {a.new_status}</strong><small>{a.note||'Status updated'} · {new Date(a.created_at).toLocaleString()}</small></li>)}</ul>}<Link className="btn btn-secondary" to="/admin/reports">View reports</Link></section></div></div>
}
