import React,{useEffect,useState} from 'react'
import {useParams} from 'react-router-dom'
import axios from 'axios'
import {authHeader} from '../../services/auth'
import {apiBase} from '../../services/apiBase'
import {applicationName} from '../../services/applicationLabel'
import FeeSummary from '../ui/FeeSummary'

const REQUEST_TIMEOUT_MS = 15000
const statuses=['Under Review','Documents Required','In Progress','Completed','Rejected','Cancelled']
const paymentPurposeLabel=(purpose:string)=>purpose==='assistance_fee'?'Assistance fee':purpose==='official_fee'?'Official fee':purpose==='request_total'?'Both fees':purpose.replace(/_/g,' ')

export default function AdminOrderDetail(){
 const {id}=useParams();const [data,setData]=useState<any|null>(null);const [status,setStatus]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [deliveryFile,setDeliveryFile]=useState<File|null>(null);const [deliveryMessage,setDeliveryMessage]=useState('');const [uploading,setUploading]=useState(false);const [deletingDocument,setDeletingDocument]=useState<number|null>(null);const [assistanceFee,setAssistanceFee]=useState('0');const [officialFee,setOfficialFee]=useState('');const [officialStatus,setOfficialStatus]=useState('unconfirmed');const [savingFees,setSavingFees]=useState(false)
 const load=async()=>{if(!id)return;setError('');try{const [orderResult,paymentResult]=await Promise.all([axios.get(`${apiBase}/admin/orders/${id}`,{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS}),axios.get(`${apiBase}/admin/orders/${id}/payments`,{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS})]);const next={...orderResult.data,payment_status:paymentResult.data};setData(next);setStatus(orderResult.data.allowed_next_statuses?.[0]||'');setAssistanceFee(String(orderResult.data.order?.fee_inr??0));setOfficialStatus(orderResult.data.order?.official_fee_status||'unconfirmed');setOfficialFee(orderResult.data.order?.official_fee_inr==null?'':String(orderResult.data.order.official_fee_inr))}catch(e:any){setError(e?.code==='ECONNABORTED'?'The server took too long to respond. Please try again.':e?.response?.data?.error||'Unable to load this request.')}}
 useEffect(()=>{load()},[id])
 const update=async()=>{if(!id||!status)return;setBusy(true);setMessage('');setError('');try{const r=await axios.post(`${apiBase}/admin/orders/${id}/status`,{status,note},{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setMessage(r.data.message);setNote('');await load()}catch(e:any){setError(e?.code==='ECONNABORTED'?'The status update timed out. Please try again.':e?.response?.data?.error||'Unable to update request status.')}finally{setBusy(false)}}
 const saveFees=async()=>{if(!id)return;setSavingFees(true);setMessage('');setError('');try{const payload:any={fee_inr:Number(assistanceFee),official_fee_status:officialStatus};if(officialStatus==='known')payload.official_fee_inr=Number(officialFee);const r=await axios.put(`${apiBase}/fees/orders/${id}`,payload,{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setMessage(`${r.data.message} Client total payable: ₹${Number(r.data.total_payable_inr||0).toFixed(2)}.`);await load()}catch(e:any){setError(e?.response?.data?.error||'Unable to update request fees.')}finally{setSavingFees(false)}}
 const deliverDocument=async(event:React.FormEvent)=>{event.preventDefault();if(!deliveryFile||!id||uploading)return;setUploading(true);setDeliveryMessage('Uploading securely…');try{const body=new FormData();body.append('file',deliveryFile);body.append('order_id',id);const response=await axios.post(`${apiBase}/uploads/`,body,{headers:authHeader(),timeout:30000});setDeliveryMessage(response.data.message);setDeliveryFile(null);await load()}catch(e:any){setDeliveryMessage(e?.code==='ECONNABORTED'?'The upload timed out. Please try again.':e?.response?.data?.error||'Unable to deliver this document.')}finally{setUploading(false)}}
 const removeDocument=async(attachment:any)=>{if(deletingDocument||!window.confirm(`Permanently remove ${attachment.filename} from private storage? This cannot be undone.`))return;setDeletingDocument(attachment.id);setError('');try{const response=await axios.delete(`${apiBase}/uploads/${attachment.id}`,{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setMessage(response.data.message);await load()}catch(e:any){setError(e?.response?.data?.error||'Unable to remove this document.')}finally{setDeletingDocument(null)}}
 if(error&&!data)return <div className="dashboard-state error-state"><h2>Request unavailable</h2><p>{error}</p><button onClick={load}>Try again</button></div>
 if(!data)return <div className="dashboard-state"><div className="loading-dot"/><p>Loading request...</p></div>
 const allowed=data.allowed_next_statuses||statuses
 const terminal=['Completed','Rejected','Cancelled'].includes(data.order.status)
 const paymentStatus=data.payment_status||{};const payments=paymentStatus.payments||[];const paid=paymentStatus.paid_components||{}
 return <div className="admin-order-detail"><h2>{applicationName(data.order)}</h2><div><strong>Request:</strong> {data.order.order_code}</div><div><strong>Client:</strong> {data.order.client_name} • {data.order.phone}</div><div><strong>Service:</strong> {data.order.service}</div><div><strong>Status:</strong> {data.order.status}</div>
  <FeeSummary data={data.order}/>
  <section className="dashboard-section"><span className="eyebrow">Client payments</span><h3>Fee and payment status</h3><p>The client can pay the assistance fee, the official/government fee, or both together when the official fee is confirmed. Captured Razorpay payments are shown below automatically.</p><div className="request-summary"><p><strong>Assistance fee:</strong> {paid.assistance_fee?'Paid':'Not paid'}</p><p><strong>Official fee:</strong> {data.order.official_fee_status==='unconfirmed'?'Not confirmed yet':paid.official_fee||Number(data.order.official_fee_inr||0)===0?'Paid / not due':'Not paid'}</p><p><strong>Overall:</strong> {paymentStatus.fully_paid?'Fully paid':'Payment still pending'}</p></div>{payments.length?<ul className="document-list">{payments.map((payment:any)=><li key={payment.id}><span><strong>{paymentPurposeLabel(payment.purpose)}</strong><small>₹{Number(payment.amount_inr||0).toFixed(2)} · {String(payment.status||'').toUpperCase()}</small>{payment.razorpay_payment_id&&<small>Razorpay payment: {payment.razorpay_payment_id}</small>}</span></li>)}</ul>:<p>No Razorpay checkout has been created for this application yet.</p>}
  {!terminal&&<><h3>Confirm or update fees</h3><p>Use ₹0 when no official fee applies. A component cannot be changed after its Razorpay checkout has been created or paid.</p><label>Assistance fee (₹)<input type="number" min="0" step="0.01" value={assistanceFee} onChange={e=>setAssistanceFee(e.target.value)}/></label><label>Official fee status<select value={officialStatus} onChange={e=>setOfficialStatus(e.target.value)}><option value="unconfirmed">Unconfirmed</option><option value="known">Known amount</option><option value="none">No official fee</option></select></label>{officialStatus==='known'&&<label>Official fee (₹)<input type="number" min="0" step="0.01" value={officialFee} onChange={e=>setOfficialFee(e.target.value)}/></label>}<button disabled={savingFees} onClick={saveFees}>{savingFees?'Saving fees…':'Save confirmed fees'}</button></>}</section>
  {!terminal&&<section className="dashboard-section"><h3>Process request</h3><p>Move the request only when the corresponding work is actually complete. Add a clear client-facing note when asking for documents or closing the request.</p><label>Next status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Select status</option>{allowed.map((s:string)=><option key={s} value={s}>{s}</option>)}</select></label><label>Processing note<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Tell the client what happened or what is needed…"/></label>{error&&<p className="info" role="alert">{error}</p>}{message&&<p className="success-message" role="status">{message}</p>}<button disabled={busy||!status} onClick={update}>{busy?'Updating…':'Update request'}</button></section>}
  {!terminal&&<section className="dashboard-section"><h3>Deliver a result document</h3><p>Upload the completed PDF or other permitted document here. It will appear securely in this client’s request and the client will receive a notification.</p><form className="upload-card" onSubmit={deliverDocument}><input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={event=>{const selected=event.target.files?.[0]||null;if(selected&&selected.size>10*1024*1024){setDeliveryMessage('Please choose a file smaller than 10 MB.');setDeliveryFile(null);return}setDeliveryFile(selected)}}/><button type="submit" disabled={!deliveryFile||uploading}>{uploading?'Delivering…':'Deliver document to client'}</button>{deliveryMessage&&<p className="info" role="status">{deliveryMessage}</p>}</form></section>}
  {terminal&&<p className="info">This request is closed and can no longer be moved to another status.</p>}
  <h3>Application</h3><div className="request-summary">{Object.entries(data.order.application_data||{}).map(([k,v])=><p key={k}><strong>{k.replace(/_/g,' ')}:</strong> {String(v||'—')}</p>)}</div>
  <h3>History</h3><ul>{(data.history||[]).map((h:any)=><li key={h.id}>{new Date(h.created_at).toLocaleString()}: {h.previous_status||'Created'} → {h.new_status} by {h.changed_by}{h.note?` — ${h.note}`:''}</li>)}</ul>
  <h3>Attachments</h3><ul className="document-list">{(data.attachments||[]).map((a:any)=><li key={a.id}><span>{a.filename} <small>({a.uploaded_by_role==='admin'?'delivered by service team':'uploaded by client'})</small></span><div className="document-actions"><button onClick={async()=>{try{const r=await fetch(`${apiBase}/uploads/${a.id}/download`,{headers:authHeader()});if(!r.ok)throw new Error();const contentType=r.headers.get('content-type')||'';if(contentType.includes('application/json')){const body=await r.json();if(body.url){window.open(body.url,'_blank','noopener,noreferrer');return}throw new Error()}const blob=await r.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=a.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setError('Download failed. Please try again.')}}}>Download</button><button className="danger-button" disabled={deletingDocument===a.id} onClick={()=>removeDocument(a)}>{deletingDocument===a.id?'Removing…':'Remove permanently'}</button></div></li>)}</ul>
  <h3>Grievances</h3><ul>{(data.grievances||[]).map((g:any)=><li key={g.id}>{g.grievance_code} — {g.status} — {g.description}</li>)}</ul><h3>Reviews</h3><ul>{(data.reviews||[]).map((r:any)=><li key={r.id}>Rating: {r.rating} — {r.comment}</li>)}</ul>
 </div>
}