import React,{useEffect,useState} from 'react'
import {fetchAdminProfile,fetchDatabaseManifest,fetchSystemReadiness,updateAdminProfile} from '../../services/admin'
import {saveToken} from '../../services/localStorage'

export default function AdminSettings(){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false)
 const [readiness,setReadiness]=useState<any>(null)
 const [databaseManifest,setDatabaseManifest]=useState<any>(null)
 useEffect(()=>{Promise.allSettled([fetchAdminProfile(),fetchSystemReadiness(),fetchDatabaseManifest()]).then(([profileResult,readinessResult,manifestResult])=>{if(profileResult.status==='fulfilled'){const r=profileResult.value;setName(r.user.name||'');setEmail(r.user.email||'');setPhone(r.user.phone||'')}else setStatus('Unable to load admin profile.');if(readinessResult.status==='fulfilled')setReadiness(readinessResult.value);if(manifestResult.status==='fulfilled')setDatabaseManifest(manifestResult.value)})},[])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setStatus('');try{const result=await updateAdminProfile({name,phone,current_password:currentPassword,new_password:newPassword});if(result.token)saveToken(result.token);setCurrentPassword('');setNewPassword('');setStatus('Profile updated successfully.')}catch(e:any){setStatus(e?.response?.data?.error||'Unable to update profile.')}finally{setBusy(false)}}
 const importantCounts=['users','services','orders','reviews','grievances','notifications','support_messages']
 return <div><div className="section-header"><div><span className="eyebrow">Administrator account</span><h2>Profile & settings</h2></div></div>{readiness&&<section className="dashboard-section"><span className="eyebrow">Public-launch readiness</span><h3>{readiness.ready?'Production configuration ready':'Production configuration needs attention'}</h3><div className="readiness-list">{readiness.checks.map((item:any)=><article className={item.ready?'readiness-item ready':'readiness-item'} key={item.key}><strong>{item.ready?'✓':'!'} {item.label}</strong><p>{item.guidance}</p></article>)}</div><h4>Manual checks</h4><ul>{readiness.manual_checks.map((item:string)=><li key={item}>{item}</li>)}</ul></section>}{databaseManifest&&<section className="dashboard-section" aria-labelledby="database-verification-heading"><span className="eyebrow">Database verification</span><h3 id="database-verification-heading">Current production database fingerprint</h3><p><strong>Provider:</strong> {databaseManifest.provider?.name||'unknown'} · <strong>Tables:</strong> {databaseManifest.tables?.length||0}</p><div className="readiness-list">{importantCounts.filter(key=>key in (databaseManifest.counts||{})).map(key=><article className="readiness-item ready" key={key}><strong>{key.replaceAll('_',' ')}</strong><p>{databaseManifest.counts[key]} records</p></article>)}</div><p><strong>Schema:</strong> <code>{databaseManifest.schema_sha256}</code></p><p><strong>Sequences:</strong> <code>{databaseManifest.sequences_sha256}</code></p><p><strong>Known launch-audit request:</strong> {databaseManifest.known_pre_migration_record?.order_count===1&&databaseManifest.known_pre_migration_record?.support_message_count===1?'Preserved':'Missing or duplicated'}</p><details><summary>Full credential-free verification manifest</summary><pre data-testid="database-manifest-json">{JSON.stringify(databaseManifest)}</pre></details></section>}<form className="dashboard-section admin-form" onSubmit={submit}><label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input disabled value={email}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><h3>Change password (optional)</h3><label>Current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>New password<input type="password" minLength={8} autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label>{status&&<p className="info" role="status">{status}</p>}<button disabled={busy}>{busy?'Saving…':'Save settings'}</button></form></div>
}
