import React,{useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {fetchAdminOverview} from '../../services/admin'

const pipeline=['Submitted','Pending','Under Review','Documents Required','In Progress','Completed','Rejected','Cancelled']

export default function AdminDashboard(){
 const [data,setData]=useState<any>({counts:{},activity:[],recent_orders:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{let active=true;fetchAdminOverview().then(r=>{if(active)setData(r)}).catch(()=>{if(active)setError('Unable to load the admin overview. Please refresh and try again.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 const counts=data.counts||{};const active=pipeline.filter(status=>!['Completed','Rejected','Cancelled'].includes(status)).reduce((total,status)=>total+(counts[status]||0),0)
 if(loading)return <div className="dashboard-state"><div className="loading-dot"/><p>Loading admin overview…</p></div>
 return <div className="admin-dashboard"><div className="dashboard-welcome"><div><span className="eyebrow">Operations overview</span><h2>Good to see you</h2><p>Review new applications, job-notice health and client support from one secure workspace.</p></div><div className="button-row"><Link className="btn btn-secondary" to="/admin/jobs">Job feed</Link><Link className="btn btn-primary" to="/admin/orders">Requests</Link></div></div>{error&&<p className="info" role="alert">{error}</p>}<div className="dashboard-stat-grid admin-stats"><div className="dashboard-stat"><span>Total requests</span><strong>{data.total_requests||0}</strong></div><div className="dashboard-stat"><span>Active</span><strong>{active}</strong></div><Link className="dashboard-stat" to="/admin/jobs"><span>Published jobs</span><strong>{data.published_job_count||0}</strong><small>{data.job_review_count||0} awaiting review</small></Link><Link className="dashboard-stat" to="/admin/orders?archive=archived"><span>Archived</span><strong>{data.archived_requests||0}</strong></Link><div className="dashboard-stat"><span>Applicable Assistance Fees</span><strong>₹{data.completed_fee_total||0}</strong></div><div className="dashboard-stat"><span>Open grievances</span><strong>{data.open_grievances||0}</strong></div><div className="dashboard-stat"><span>Clients</span><strong>{data.client_count||0}</strong></div><div className="dashboard-stat"><span>Rating</span><strong>{data.average_rating||0}/5</strong></div></div><div className="admin-dashboard-grid"><section className="dashboard-section"><h2>Request pipeline</h2><div className="pipeline-list">{pipeline.map(label=><Link className="pipeline-row" key={label} to={`/admin/orders?status=${encodeURIComponent(label)}`}><span className="pipeline-label"><strong>{label}</strong></span><span className="pipeline-count">{counts[label]||0}</span></Link>)}</div></section><section className="dashboard-section"><h2>Recent activity</h2>{!data.activity?.length?<p>No activity yet.</p>:<ul className="activity-list">{data.activity.slice(0,8).map((item:any)=><li key={item.id}><strong>{item.previous_status||'Created'} → {item.new_status}</strong><small>{item.note||'Status updated'} · {new Date(item.created_at).toLocaleString()}</small></li>)}</ul>}<Link className="btn btn-secondary" to="/admin/reports">Reports</Link></section></div></div>
}
