import React,{useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {fetchAdminOrders} from '../../services/admin'

const REQUEST_STATUSES=['New','Under Review','Documents Required','In Progress','Completed']

export default function AdminDashboard(){
 const [meta,setMeta]=useState<any>({});const [counts,setCounts]=useState<any>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{let active=true;(async()=>{try{const [total,...results]=await Promise.all([fetchAdminOrders(1,1,''),...REQUEST_STATUSES.map(s=>fetchAdminOrders(1,1,s))]);if(!active)return;setMeta(total.meta||{});const next:any={};REQUEST_STATUSES.forEach((s,i)=>{next[s]=results[i]?.meta?.total||0});setCounts(next)}catch(e){if(active)setError('Unable to load the admin overview. Please refresh and try again.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[])
 const active=useMemo(()=>['New','Under Review','Documents Required','In Progress'].reduce((n,s)=>n+(counts[s]||0),0),[counts])
 if(loading)return <div className="dashboard-state"><div className="loading-dot"/><p>Loading admin overview…</p></div>
 return <div className="admin-dashboard"><div className="dashboard-welcome"><div><span className="eyebrow">Operations overview</span><h2>Admin workspace</h2><p>Monitor requests, resolve issues and keep services moving.</p></div><Link className="btn btn-primary" to="/admin/orders">Review requests</Link></div>{error&&<p className="info" role="alert">{error}</p>}<div className="dashboard-stat-grid admin-stats"><div className="dashboard-stat"><span>Total requests</span><strong>{meta.total??0}</strong><small>All citizen requests</small></div><div className="dashboard-stat"><span>Active work</span><strong>{active}</strong><small>Needs attention</small></div><div className="dashboard-stat"><span>New</span><strong>{counts.New??0}</strong><small>Recently submitted</small></div><div className="dashboard-stat"><span>Completed</span><strong>{counts.Completed??0}</strong><small>Successfully delivered</small></div></div><div className="admin-dashboard-grid"><section className="dashboard-section"><div className="section-header inline"><div><span className="eyebrow">Work queue</span><h2>Request pipeline</h2></div></div><div className="pipeline-list">{[['New',counts.New,'Review newly submitted requests'],['Under Review',counts['Under Review'],'Requests being checked'],['Documents Required',counts['Documents Required'],'Waiting for client documents'],['In Progress',counts['In Progress'],'Requests currently being handled'],['Completed',counts.Completed,'Recently completed services']].map(([label,count,hint])=><Link className="pipeline-row" key={String(label)} to={`/admin/orders?status=${encodeURIComponent(String(label))}`}><span className="pipeline-label"><strong>{label}</strong><small>{hint}</small></span><span className="pipeline-count">{count as number||0}</span></Link>)}</div></section><section className="dashboard-section quick-actions"><div className="section-header inline"><div><span className="eyebrow">Shortcuts</span><h2>Quick actions</h2></div></div><Link to="/admin/orders" className="action-card"><span>Requests</span><small>Review and update citizen requests →</small></Link><Link to="/admin/services" className="action-card"><span>Services</span><small>Manage the public service catalogue →</small></Link><Link to="/admin/grievances" className="action-card"><span>Grievances</span><small>Respond to citizen concerns →</small></Link><Link to="/admin/reviews" className="action-card"><span>Reviews</span><small>Monitor feedback and trust signals →</small></Link></section></div></div>
}
