import React,{useEffect,useState} from 'react'
import {clearJobFeeRules,saveJobFeeRules} from '../../services/jobFeeAdmin'
import {JobNotification} from '../../services/jobs'

export default function JobFeeRuleEditor({job,onSaved,onClose}:{job:JobNotification;onSaved:(job:JobNotification)=>void;onClose:()=>void}){
 const [factors,setFactors]=useState(JSON.stringify(job.fee_factors||[],null,2))
 const [rules,setRules]=useState(JSON.stringify(job.fee_rules||[],null,2))
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>{setFactors(JSON.stringify(job.fee_factors||[],null,2));setRules(JSON.stringify(job.fee_rules||[],null,2));setMessage('');setError('')},[job.id])
 const save=async()=>{setBusy(true);setError('');setMessage('');try{const parsedFactors=JSON.parse(factors),parsedRules=JSON.parse(rules);const result=await saveJobFeeRules(job.id,parsedFactors,parsedRules);setMessage(result.message);onSaved(result.job)}catch(e:any){setError(e?.response?.data?.error||e?.message||'Unable to save fee rules.')}finally{setBusy(false)}}
 const clear=async()=>{if(!window.confirm('Clear verified automatic fee rules for this job? Payment will then wait for manual fee confirmation.'))return;setBusy(true);setError('');try{const result=await clearJobFeeRules(job.id);setMessage(result.message);onSaved(result.job);setFactors('[]');setRules('[]')}catch(e:any){setError(e?.response?.data?.error||'Unable to clear fee rules.')}finally{setBusy(false)}}
 return <section className="dashboard-section"><div className="section-header inline"><div><span className="eyebrow">Person-specific official fee</span><h3>{job.title}</h3><p>Open the official notification and include every applicant condition that can change the fee. Do not guess. Automatic calculation is enabled only after you save these rules as verified.</p></div><button className="btn btn-secondary" onClick={onClose}>Close</button></div><p><a href={job.official_notice_url} target="_blank" rel="noopener noreferrer">Open official notification ↗</a></p><label>Fee-determining factors (JSON)<textarea rows={10} value={factors} onChange={e=>setFactors(e.target.value)} placeholder={'[{"key":"category","label":"Category","type":"select","options":["General","SC","ST"]}]'}/></label><small>Use only factors actually mentioned in this notification. Supported types: select, text, boolean.</small><label>Fee rules (JSON)<textarea rows={12} value={rules} onChange={e=>setRules(e.target.value)} placeholder={'[{"label":"Exempt category","priority":100,"amount_inr":0,"conditions":{"category":["SC","ST"]}},{"label":"Standard fee","priority":0,"amount_inr":100,"conditions":{}}]'}/></label><small>Higher priority wins when more than one rule matches. Include a fallback rule when the notification has a standard fee.</small>{message&&<p className="success-message" role="status">{message}</p>}{error&&<p className="info" role="alert">{error}</p>}<div className="cta-row"><button disabled={busy} onClick={save}>{busy?'Saving…':'Save as verified from official notification'}</button><button className="danger-button" disabled={busy} onClick={clear}>Clear automatic rules</button></div></section>
}
