import React,{useEffect,useState} from 'react'
import {fetchAdminJobs,fetchAdminJobSources,synchronizeJobs,updateAdminJob} from '../../services/admin'
import {formatJobDate,JobNotification,JobSource} from '../../services/jobs'

const statuses=['','published','needs_review','expired','hidden']

export default function JobManagement(){
  const [jobs,setJobs]=useState<JobNotification[]>([]);const [sources,setSources]=useState<JobSource[]>([]);const [counts,setCounts]=useState<Record<string,number>>({});const [status,setStatus]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [syncing,setSyncing]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');try{const [jobData,sourceData]=await Promise.all([fetchAdminJobs({status,q:query,per_page:100}),fetchAdminJobSources()]);setJobs(jobData.items||[]);setCounts(jobData.counts||{});setSources(sourceData.items||[])}catch{setError('Unable to load job-feed management.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[status])
  const save=async(job:JobNotification,changes:any)=>{setError('');try{const result=await updateAdminJob(job.id,changes);setJobs(items=>items.map(item=>item.id===job.id?result.job:item));setMessage('Job notice updated.')}catch(err:any){setError(err?.response?.data?.error||'Unable to update this notice.')}}
  const sync=async()=>{setSyncing(true);setMessage('');setError('');try{const result=await synchronizeJobs();setMessage(`Official-source check completed: ${result.successful_sources} source(s) succeeded and ${result.expired} expired notice(s) were closed.`);await load()}catch(err:any){setError(err?.response?.data?.error||'The official-source check did not complete. Source health below shows the latest state.');await load()}finally{setSyncing(false)}}
  return <div className="job-admin"><section className="job-admin-summary"><div className="job-admin-stat blue"><span>Published</span><strong>{counts.published||0}</strong></div><div className="job-admin-stat orange"><span>Needs review</span><strong>{counts.needs_review||0}</strong></div><div className="job-admin-stat gray"><span>Expired</span><strong>{counts.expired||0}</strong></div><div className="job-admin-stat green"><span>Official sources</span><strong>{sources.length}</strong></div></section>
    <section className="dashboard-section"><div className="section-header inline"><div><span className="eyebrow">Daily verified pipeline</span><h2>Job Feed Management</h2><p>Only allowlisted official HTTPS sources are synchronized. Ambiguous notices stay hidden for review.</p></div><button className="btn btn-primary" disabled={syncing} onClick={sync}>{syncing?'Checking official sources…':'Synchronize now'}</button></div>{message&&<p className="info success-info" role="status">{message}</p>}{error&&<p className="info error-info" role="alert">{error}</p>}<div className="job-source-health">{sources.map(source=><article key={source.key}><span className={`source-status ${source.last_sync_status==='success'?'healthy':source.last_sync_status==='failed'?'failed':''}`}/><div><strong>{source.name}</strong><small>{source.last_sync_status==='success'?'Healthy':source.last_sync_status==='failed'?'Needs attention':'Awaiting first run'} · {source.last_sync_completed_at?new Date(source.last_sync_completed_at).toLocaleString('en-IN'):'Not checked yet'}</small>{source.last_error&&<p>{source.last_error}</p>}</div><a href={source.listing_url} target="_blank" rel="noopener noreferrer">Official source ↗</a></article>)}</div></section>
    <section className="dashboard-section"><div className="admin-filters job-admin-filters"><label>Search notices<input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')load()}} placeholder="Title, organization or qualification"/></label><label>Status<select value={status} onChange={event=>setStatus(event.target.value)}>{statuses.map(value=><option value={value} key={value}>{value?value.replace('_',' '):'All statuses'}</option>)}</select></label><button onClick={load}>Search</button></div>{loading?<div className="dashboard-state"><div className="loading-dot"/><p>Loading notices…</p></div>:!jobs.length?<div className="empty-dashboard"><h3>No notices in this view</h3></div>:<div className="table-scroll"><table className="table job-admin-table"><thead><tr><th>Notice</th><th>Details extracted</th><th>Deadline</th><th>Verification</th><th>Publishing</th></tr></thead><tbody>{jobs.map(job=><tr key={job.id}><td><span className={`job-type-badge ${job.job_type}`}>{job.job_type}</span><strong>{job.title}</strong><small>{job.organization}<br/>{job.source?.name}</small></td><td><small>Qualification</small>{job.qualification||'—'}<br/><small>Age</small>{job.age_limit||'—'}<br/><small>Fee</small>{job.application_fee||'—'}</td><td>{formatJobDate(job.deadline)}</td><td><span className="verified-source">✓ {job.verification_status.replaceAll('_',' ')}</span><small>Confidence {Math.round((job.confidence||0)*100)}%</small></td><td><label>Status<select value={job.status} onChange={event=>save(job,{status:event.target.value})}><option value="published">Published</option><option value="needs_review">Needs review</option><option value="expired">Expired</option><option value="hidden">Hidden</option></select></label><label className="feature-check"><input type="checkbox" checked={job.is_featured} onChange={event=>save(job,{is_featured:event.target.checked})}/> Highlight on public pages</label><a href={job.official_notice_url} target="_blank" rel="noopener noreferrer">Review source ↗</a></td></tr>)}</tbody></table></div>}</section>
  </div>
}
