import React,{useEffect,useState} from 'react'
import axios from 'axios'
import {fetchAdminJobs,fetchAdminJobSources,synchronizeJobs,updateAdminJob} from '../../services/admin'
import {fetchJobs,fetchJobSources,formatJobDate,JobNotification,JobSource} from '../../services/jobs'
import {authHeader} from '../../services/auth'
import {apiBase} from '../../services/apiBase'
import JobFeeRuleEditor from './JobFeeRuleEditor'

const statuses=['','published','needs_review','expired','hidden']

function sourceState(source:JobSource){
 if(source.last_sync_status==='success')return {label:'Healthy',className:'healthy'}
 if(source.last_sync_status==='degraded')return {label:'Using last verified data',className:'healthy'}
 if(source.last_sync_status==='failed')return {label:'Needs attention',className:'failed'}
 if(source.last_sync_status==='running')return {label:'Checking now',className:''}
 return {label:'Awaiting first run',className:''}
}

function sourceNote(source:JobSource){
 if(source.last_sync_status==='degraded')return 'The official website is temporarily unavailable. Previously verified notices remain available.'
 if(source.last_sync_status==='failed')return 'The official website could not be checked right now. Existing verified notices are kept and the next scheduled check will retry automatically.'
 return ''
}

export default function JobManagement(){
  const [jobs,setJobs]=useState<JobNotification[]>([]);const [sources,setSources]=useState<JobSource[]>([]);const [counts,setCounts]=useState<Record<string,number>>({});const [status,setStatus]=useState('');const [query,setQuery]=useState(()=>new URLSearchParams(window.location.search).get('q')||'');const [loading,setLoading]=useState(true);const [syncing,setSyncing]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [readOnly,setReadOnly]=useState(false);const [jobFee,setJobFee]=useState('30');const [savingFee,setSavingFee]=useState(false);const [feeJob,setFeeJob]=useState<JobNotification|null>(null)
  const load=async()=>{setLoading(true);setError('');try{const [jobData,sourceData,feeData]=await Promise.all([fetchAdminJobs({status,q:query,per_page:100}),fetchAdminJobSources(),axios.get(`${apiBase}/fees/job-assistance`,{timeout:12000})]);setJobs(jobData.items||[]);setCounts(jobData.counts||{});setSources(sourceData.items||[]);setJobFee(String(feeData.data?.price_inr??30));setReadOnly(false)}catch{try{const [jobData,sourceData]=await Promise.all([fetchJobs({q:query,limit:100}),fetchJobSources()]);const publicItems=status&&status!=='published'?[]:(jobData.items||[]);setJobs(publicItems);setCounts({published:jobData.count||0,needs_review:jobData.review_count||0,expired:0,hidden:0});setSources(sourceData.items||[]);setReadOnly(true);setMessage('The verified daily snapshot is shown in read-only mode while the live management API starts. Public job search remains available.')}catch{setError('Unable to load the live feed or the verified daily snapshot.')}}finally{setLoading(false)}}
  useEffect(()=>{load()},[status])
  const save=async(job:JobNotification,changes:any)=>{if(readOnly)return;setError('');try{const result=await updateAdminJob(job.id,changes);setJobs(items=>items.map(item=>item.id===job.id?result.job:item));setMessage('Job notice updated.')}catch(err:any){setError(err?.response?.data?.error||'Unable to update this notice.')}}
  const saveFee=async()=>{const amount=Number(jobFee);if(!Number.isFinite(amount)||amount<0){setError('Enter a valid job assistance fee of ₹0 or more.');return}setSavingFee(true);setError('');setMessage('');try{const r=await axios.put(`${apiBase}/fees/job-assistance`,{price_inr:amount},{headers:authHeader(),timeout:12000});setJobFee(String(r.data.price_inr));setMessage(r.data.message)}catch(err:any){setError(err?.response?.data?.error||'Unable to update the job assistance fee.')}finally{setSavingFee(false)}}
  const sync=async()=>{if(readOnly)return;setSyncing(true);setMessage('');setError('');try{const result=await synchronizeJobs();const degraded=Number(result.degraded_sources||0);setMessage(`Official-source check completed: ${result.successful_sources} source(s) refreshed${degraded?`, ${degraded} temporarily unavailable source(s) kept their last verified data`:''}, and ${result.expired} expired notice(s) were closed.`);await load()}catch(err:any){setError(err?.response?.data?.error||'The official-source check did not complete. Existing verified notices remain available where possible; source health below shows the latest state.');await load()}finally{setSyncing(false)}}
  const feeSaved=(updated:JobNotification)=>{setJobs(items=>items.map(item=>item.id===updated.id?updated:item));setFeeJob(updated)}
  return <div className="job-admin"><section className="job-admin-summary"><div className="job-admin-stat blue"><span>Published</span><strong>{counts.published||0}</strong></div><div className="job-admin-stat orange"><span>Needs review</span><strong>{counts.needs_review||0}</strong></div><div className="job-admin-stat gray"><span>Expired</span><strong>{counts.expired||0}</strong></div><div className="job-admin-stat green"><span>Official sources</span><strong>{sources.length}</strong></div></section>
    <section className="dashboard-section"><span className="eyebrow">Website-wide job pricing</span><h2>Job application assistance fee</h2><p>Set one assistance fee for every official job application. ₹0 is allowed. Existing submitted requests keep the fee they already accepted.</p><div className="admin-filters"><label>Assistance fee (₹)<input type="number" min="0" step="0.01" value={jobFee} onChange={e=>setJobFee(e.target.value)}/></label><button className="btn btn-primary" disabled={savingFee||readOnly} onClick={saveFee}>{savingFee?'Saving…':'Save job fee'}</button></div></section>
    <section className="dashboard-section"><div className="section-header inline"><div><span className="eyebrow">Daily verified pipeline</span><h2>Job Feed Management</h2><p>Only allowlisted official HTTPS sources are synchronized. Temporary official-site outages are retried automatically and do not remove previously verified job notices.</p></div><button className="btn btn-primary" disabled={syncing||readOnly} onClick={sync}>{readOnly?'Automatic daily refresh':syncing?'Checking official sources…':'Synchronize now'}</button></div>{message&&<p className="info success-info" role="status">{message}</p>}{error&&<p className="info error-info" role="alert">{error}</p>}<div className="job-source-health">{sources.map(source=>{const health=sourceState(source);const note=sourceNote(source);return <article key={source.key}><span className={`source-status ${health.className}`}/><div><strong>{source.name}</strong><small>{health.label} · {source.last_sync_completed_at?new Date(source.last_sync_completed_at).toLocaleString('en-IN'):'Not checked yet'}</small>{note&&<p>{note}</p>}</div><a href={source.listing_url} target="_blank" rel="noopener noreferrer">Official source ↗</a></article>})}</div></section>
    {feeJob&&<JobFeeRuleEditor job={feeJob} onSaved={feeSaved} onClose={()=>setFeeJob(null)}/>}    
    <section className="dashboard-section"><div className="admin-filters job-admin-filters"><label>Search notices<input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')load()}} placeholder="Title, organization or qualification"/></label><label>Status<select value={status} onChange={event=>setStatus(event.target.value)}>{statuses.map(value=><option value={value} key={value}>{value?value.replace('_',' '):'All statuses'}</option>)}</select></label><button onClick={load}>Search</button></div>{loading?<div className="dashboard-state"><div className="loading-dot"/><p>Loading notices…</p></div>:!jobs.length?<div className="empty-dashboard"><h3>No notices in this view</h3></div>:<div className="table-scroll"><table className="table job-admin-table"><thead><tr><th>Notice</th><th>Details extracted</th><th>Deadline</th><th>Verification</th><th>Publishing</th></tr></thead><tbody>{jobs.map(job=><tr key={job.id}><td><span className={`job-type-badge ${job.job_type}`}>{job.job_type}</span><strong>{job.title}</strong><small>{job.organization}<br/>{job.source?.name}</small></td><td><small>Qualification</small>{job.qualification||'—'}<br/><small>Age</small>{job.age_limit||'—'}<br/><small>Official fee text</small>{job.application_fee||'—'}<br/><small>Person-specific fee rules</small>{job.fee_rules_verified?`Verified · ${job.fee_factors?.length||0} factor(s)`:'Needs verification'}</td><td>{formatJobDate(job.deadline)}</td><td><span className="verified-source">✓ {job.verification_status.replaceAll('_',' ')}</span><small>Confidence {Math.round((job.confidence||0)*100)}%</small><button className="btn-secondary" disabled={readOnly} onClick={()=>setFeeJob(job)}>{job.fee_rules_verified?'Review fee rules':'Configure fee rules'}</button></td><td><label>Status<select disabled={readOnly} value={job.status} onChange={event=>save(job,{status:event.target.value})}><option value="published">Published</option><option value="needs_review">Needs review</option><option value="expired">Expired</option><option value="hidden">Hidden</option></select></label><label className="feature-check"><input type="checkbox" disabled={readOnly} checked={job.is_featured} onChange={event=>save(job,{is_featured:event.target.checked})}/> Highlight on public pages</label><a href={job.official_notice_url} target="_blank" rel="noopener noreferrer">Review source ↗</a></td></tr>)}</tbody></table></div>}</section>
  </div>
}
