import React,{useEffect,useState} from 'react'
import {fetchAdminMessageThread,fetchAdminMessageThreads,markAdminMessageThreadRead,sendAdminSupportMessage} from '../../services/admin'

export default function MessageManagement(){
 const [threads,setThreads]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [message,setMessage]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 const loadThreads=()=>{setLoading(true);setError('');fetchAdminMessageThreads().then(data=>setThreads(data.items||[])).catch(()=>setError('Unable to load client messages.')).finally(()=>setLoading(false))}
 useEffect(()=>{loadThreads();const timer=window.setInterval(loadThreads,12000);return()=>window.clearInterval(timer)},[])
 useEffect(()=>{if(!selected?.user?.id)return;const userId=selected.user.id;const timer=window.setInterval(()=>{fetchAdminMessageThread(userId).then(data=>setSelected(data)).catch(()=>{})},10000);return()=>window.clearInterval(timer)},[selected?.user?.id])
 const open=async(userId:number)=>{setError('');try{const data=await fetchAdminMessageThread(userId);setSelected(data);await markAdminMessageThreadRead(userId);setThreads(current=>current.map(item=>item.user.id===userId?{...item,unread:0}:item))}catch{setError('Unable to open this conversation.')}}
 const send=async(event:React.FormEvent)=>{event.preventDefault();if(!selected||!message.trim()||busy)return;setBusy(true);setError('');try{const data=await sendAdminSupportMessage(selected.user.id,message.trim());setSelected((current:any)=>({...current,items:[...(current?.items||[]),data.item]}));setMessage('');loadThreads()}catch(err:any){setError(err?.response?.data?.error||'Unable to send this reply.')}finally{setBusy(false)}}
 return <section className="dashboard-section"><div className="section-header"><div><span className="eyebrow">Client communication</span><h2>Private messages</h2><p>Reply to account-owned support conversations. Never ask clients for OTPs, passwords, PINs or banking credentials.</p></div><button className="btn btn-secondary" onClick={loadThreads} disabled={loading}>Refresh</button></div>{error&&<p className="info" role="alert">{error}</p>}
  <div className="admin-message-layout"><aside className="message-thread-list" aria-label="Client conversations">{loading?<p>Loading conversations…</p>:threads.length===0?<p>No client messages yet.</p>:threads.map(thread=><button type="button" className={selected?.user?.id===thread.user.id?'active':''} onClick={()=>open(thread.user.id)} key={thread.user.id}><span><strong>{thread.user.name||'Client'}</strong>{thread.unread>0&&<b>{thread.unread} new</b>}</span><small>{thread.user.email}</small><p>{thread.latest_message.message}</p></button>)}</aside>
   <div className="admin-message-thread">{!selected?<div className="empty-dashboard"><h3>Select a conversation</h3><p>Choose a client to read and reply.</p></div>:<><div className="message-client-header"><h3>{selected.user.name}</h3><p>{selected.user.email} · {selected.user.phone||'No phone'}</p></div><div className="chat-thread">{selected.items.map((item:any)=><article key={item.id} className={`chat-bubble ${item.sender_role==='admin'?'chat-admin':'chat-client'}`}><strong>{item.sender_role==='admin'?'Service team':'Client'}</strong><p>{item.message}</p><small>{new Date(item.created_at).toLocaleString()}</small></article>)}</div><form className="chat-composer" onSubmit={send}><label htmlFor="admin-support-reply">Reply</label><div><textarea id="admin-support-reply" rows={3} maxLength={2000} value={message} onChange={event=>setMessage(event.target.value)} placeholder="Write a clear client-visible reply…"/><button disabled={busy||!message.trim()}>{busy?'Sending…':'Send reply'}</button></div></form></>}</div>
  </div>
 </section>
}
