import React,{useEffect,useState} from 'react'
import {fetchAdminUsers,sendClientNotification} from '../../services/admin'

export default function NotificationManagement(){
 const [users,setUsers]=useState<any[]>([]),[userId,setUserId]=useState(''),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[permission,setPermission]=useState(typeof Notification==='undefined'?'unsupported':Notification.permission)
 useEffect(()=>{fetchAdminUsers(1,'').then(r=>setUsers(r.items||[])).catch(()=>setStatus('Unable to load clients.'))},[])
 const enablePhoneNotifications=async()=>{if(typeof Notification==='undefined'){setStatus('Browser notifications are not supported on this device.');return}const result=await Notification.requestPermission();setPermission(result);if(result==='granted'){setStatus('Phone/browser notifications enabled on this device. Keep this site installed or allowed to send notifications.');const reg=await navigator.serviceWorker?.ready;reg?.active?.postMessage({type:'SHOW_ADMIN_NOTIFICATION',title:'Admin alerts enabled',body:'This device can now show free browser notifications from Public Online Service Provider.',url:'/admin/notifications',tag:'admin-alert-test'})}else setStatus('Notification permission was not enabled. You can allow it later in your browser site settings.')}
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setStatus('');try{await sendClientNotification({user_id:Number(userId),title,message});setTitle('');setMessage('');setStatus('Notification sent successfully.')}catch(e:any){setStatus(e?.response?.data?.error||'Unable to send notification.')}finally{setBusy(false)}}
 return <div><div className="section-header"><div><span className="eyebrow">Client communication</span><h2>Notifications</h2><p>Use in-site notifications and free browser/Android alerts without a paid SMS provider.</p></div></div><section className="dashboard-section"><h3>Admin phone alerts</h3><p>Enable notifications on each admin phone or computer where you want browser alerts. This does not require Twilio or paid SMS.</p><button type="button" onClick={enablePhoneNotifications} disabled={permission==='granted'||permission==='unsupported'}>{permission==='granted'?'Notifications enabled':permission==='unsupported'?'Not supported':'Enable notifications on this device'}</button></section><form className="dashboard-section admin-form" onSubmit={submit}><label>Client<select required value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Select client</option>{users.map(u=><option value={u.id} key={u.id}>{u.name||u.email} — {u.email}</option>)}</select></label><label>Title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Message<textarea required rows={6} maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/></label>{status&&<p className="info" role="status">{status}</p>}<button disabled={busy}>{busy?'Sending…':'Send notification'}</button></form></div>
}
