import React,{useEffect,useState} from 'react'
import {Link,useSearchParams} from 'react-router-dom'
import {fetchAdminOrders,setOrderArchived} from '../../services/admin'

const STATUSES=['','Submitted','Pending','Under Review','Documents Required','In Progress','Completed','Rejected','Cancelled']

export default function OrderManagement(){
 const [params,setParams]=useSearchParams();const status=params.get('status')||''
 const archiveView=['active','archived','all'].includes(params.get('archive')||'')?(params.get('archive') as 'active'|'archived'|'all'):'active'
 const [orders,setOrders]=useState<any[]>([]);const [meta,setMeta]=useState<any>({});const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [message,setMessage]=useState('');const [changingArchive,setChangingArchive]=useState<number|null>(null);const [q,setQ]=useState('');const [dateFrom,setDateFrom]=useState('');const [dateTo,setDateTo]=useState('')
 const load=async(p=1)=>{setLoading(true);setError('');try{const res=await fetchAdminOrders(p,20,status,q,dateFrom,dateTo,archiveView);setOrders(res.items||[]);setMeta(res.meta||{})}catch(err:any){setError(err?.response?.data?.error||'Unable to load requests. Please try again.')}finally{setLoading(false)}}
 const changeArchive=async(order:any,archived:boolean)=>{if(archived&&!window.confirm(`Archive ${order.order_code} from the admin queue? The client will still see the complete application and history.`))return;setChangingArchive(order.id);setError('');setMessage('');try{const result=await setOrderArchived(order.id,archived);setMessage(result.message);await load(page)}catch(err:any){setError(err?.response?.data?.error||'Unable to update the admin application list.')}finally{setChangingArchive(null)}}
 useEffect(()=>{setPage(1)},[status,archiveView])
 useEffect(()=>{load(page)},[page,status,archiveView])
 const heading=archiveView==='archived'?'Archived applications':archiveView==='all'?'All applications':status||'Current applications'
 return <div className="admin-orders"><div className="section-header"><div><span className="eyebrow">Request queue</span><h2>{heading}</h2><p>Archiving only cleans the admin queue. It never removes an application from the client dashboard or client history.</p></div></div>
  <div className="admin-filters"><label>Search<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Request ID, client, phone or service"/></label><label>Status<select value={status} onChange={e=>{const next=e.target.value;if(next)params.set('status',next);else params.delete('status');setParams(params)}}>{STATUSES.map(s=><option key={s} value={s}>{s||'All statuses'}</option>)}</select></label><label>Admin list<select value={archiveView} onChange={e=>{const next=e.target.value;if(next==='active')params.delete('archive');else params.set('archive',next);setParams(params)}}><option value="active">Current applications</option><option value="archived">Archived applications</option><option value="all">All applications</option></select></label><label>From<input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label>To<input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><button onClick={()=>{setPage(1);load(1)}}>Apply filters</button></div>
  {message&&<p className="success-message" role="status">{message}</p>}
  {error&&<div className="dashboard-state error-state"><p>{error}</p><button onClick={()=>load(page)}>Try again</button></div>}
  {loading?<div className="dashboard-state"><div className="loading-dot"/><p>Loading…</p></div>:!orders.length&&!error?<div className="dashboard-state"><p>{archiveView==='archived'?'No archived applications.':'No requests found.'}</p></div>:<ul className="admin-record-list">{orders.map(o=><li key={o.id}><div className="admin-record-main"><span className="request-code">{o.order_code}</span><strong>{o.service}</strong><small>{o.client_name} · {o.phone}</small>{o.is_archived&&<small>Archived {new Date(o.archived_at).toLocaleString()}</small>}</div><span className={`status-pill status-${String(o.status||'').toLowerCase().replace(/\s+/g,'-')}`}>{o.status}</span><div className="admin-record-fees"><small>Applicable Assistance Fee ₹{o.fee_inr}</small><small>Official fee: {o.official_fee_status==='unconfirmed'?'To be confirmed':`₹${o.official_fee_inr||0}`}</small></div><div className="admin-record-actions"><Link className="btn btn-secondary" to={`/admin/orders/${o.id}`}>Open</Link>{o.is_archived?<button className="btn-secondary" disabled={changingArchive===o.id} onClick={()=>changeArchive(o,false)}>{changingArchive===o.id?'Restoring…':'Restore'}</button>:['Completed','Rejected','Cancelled'].includes(o.status)&&<button className="btn-secondary" disabled={changingArchive===o.id} onClick={()=>changeArchive(o,true)}>{changingArchive===o.id?'Archiving…':'Archive'}</button>}</div></li>)}</ul>}
  <div className="pagination"><button disabled={loading||page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>Page {meta.page??page} of {meta.pages??1}</span><button disabled={loading||page>=(meta.pages??1)} onClick={()=>setPage(p=>p+1)}>Next</button></div>
 </div>
}
