import React,{useEffect,useState} from 'react'
import {fetchServices,createService,updateService,setServiceActive} from '../../services/admin'
import FeeSummary from '../ui/FeeSummary'

type OfficialStatus='known'|'none'|'unconfirmed'
export default function ServiceManagement(){
 const [services,setServices]=useState<any[]>([]);const [name,setName]=useState('');const [desc,setDesc]=useState('');const [price,setPrice]=useState(30);const [officialStatus,setOfficialStatus]=useState<OfficialStatus>('unconfirmed');const [officialFee,setOfficialFee]=useState<number|''>('');const [editing,setEditing]=useState<number|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const load=async()=>{try{setServices(await fetchServices())}catch{setError('Unable to load services.')}}
 useEffect(()=>{load()},[])
 const reset=()=>{setName('');setDesc('');setPrice(30);setOfficialStatus('unconfirmed');setOfficialFee('');setEditing(null)}
 const save=async()=>{try{setBusy(true);setError('');if(price<0){setError('Assistance fee cannot be negative.');return}if(officialStatus==='known'&&(officialFee===''||Number(officialFee)<0)){setError('Enter the confirmed official fee.');return}const payload={name,description:desc,price_inr:price,official_fee_status:officialStatus,official_fee_inr:officialStatus==='known'?Number(officialFee):officialStatus==='none'?0:null};if(editing)await updateService(editing,payload);else await createService(payload);reset();await load()}catch(err:any){const value=err?.response?.data?.error;setError(typeof value==='string'?value:'Unable to save service.')}finally{setBusy(false)}}
 const edit=(service:any)=>{setEditing(service.id);setName(service.name);setDesc(service.description||'');setPrice(service.price_inr||0);setOfficialStatus(service.official_fee_status||'unconfirmed');setOfficialFee(service.official_fee_inr??'');window.scrollTo({top:0,behavior:'smooth'})}
 const toggle=async(service:any)=>{try{await setServiceActive(service.id,!service.is_active);await load()}catch{setError('Unable to update service availability.')}}
 return <div><div className="section-header"><div><span className="eyebrow">Catalog pricing</span><h2>Service Management</h2><p>Configure your private assistance fee separately from government or official charges.</p></div></div>{error&&<p className="info" role="alert">{error}</p>}<div className="dashboard-section admin-form service-admin-form"><label>Service name<input placeholder="Service name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Description<input placeholder="What assistance is provided?" value={desc} onChange={e=>setDesc(e.target.value)}/></label><label>Our assistance fee (₹)<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/><small>This is your configurable private assistance charge, not a government fee.</small></label><label>Government / official fee status<select value={officialStatus} onChange={e=>setOfficialStatus(e.target.value as OfficialStatus)}><option value="unconfirmed">To be confirmed</option><option value="none">No official fee</option><option value="known">Known exact amount</option></select></label>{officialStatus==='known'&&<label>Government / official fee (₹)<input type="number" min="0" step="0.01" value={officialFee} onChange={e=>setOfficialFee(e.target.value===''?'':Number(e.target.value))}/></label>}<FeeSummary data={{price_inr:price,official_fee_status:officialStatus,official_fee_inr:officialStatus==='known'?Number(officialFee):officialStatus==='none'?0:null}} compact/><div className="button-row"><button disabled={busy||name.trim().length<2} onClick={save}>{busy?'Saving…':editing?'Save changes':'Add service'}</button>{editing&&<button className="btn-secondary" onClick={reset}>Cancel edit</button>}</div></div><ul className="admin-service-list">{services.map(service=><li key={service.id}><div><strong>{service.name}</strong><p>{service.description}</p><small>Category: {service.category||'Not assigned'} · {service.is_active?'Active':'Disabled'}</small></div><FeeSummary data={service} compact/><div className="button-row"><button onClick={()=>edit(service)}>Edit</button><button className="btn-secondary" onClick={()=>toggle(service)}>{service.is_active?'Disable':'Enable'}</button></div></li>)}</ul></div>
}
