import React,{useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {
  createCategory,createService,fetchAdminJobs,fetchCategories,fetchServices,setServiceActive,
  fetchHomepageAssistanceFee,fetchJobAssistanceFee,fetchScholarshipAssistanceFee,fetchRechargeBillAssistanceFee,
  updateAllAssistanceFees,updateHomepageAssistanceFee,updateJobAssistanceFee,
  updateScholarshipAssistanceFee,updateRechargeBillAssistanceFee,updateService,
} from '../../services/admin'
import FeeSummary from '../ui/FeeSummary'

type OfficialStatus='known'|'none'|'unconfirmed'
export default function ServiceManagement(){
 const [services,setServices]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([])
 const [name,setName]=useState(''),[desc,setDesc]=useState(''),[keywords,setKeywords]=useState(''),[categoryId,setCategoryId]=useState(''),[newCategory,setNewCategory]=useState('')
 const [price,setPrice]=useState(30),[officialStatus,setOfficialStatus]=useState<OfficialStatus>('unconfirmed'),[officialFee,setOfficialFee]=useState<number|''>(''),[editing,setEditing]=useState<number|null>(null)
 const [globalFee,setGlobalFee]=useState<number|''>(30),[globalConfirmed,setGlobalConfirmed]=useState(false),[homepageFee,setHomepageFee]=useState<number|''>(30),[jobFee,setJobFee]=useState<number|''>(30),[scholarshipFee,setScholarshipFee]=useState<number|''>(30),[rechargeFee,setRechargeFee]=useState<number|''>(10)
 const [searchQuery,setSearchQuery]=useState(''),[jobResults,setJobResults]=useState<any[]>([]),[searching,setSearching]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{try{setError('');const [ss,cc,h,j,s,r]=await Promise.all([fetchServices(),fetchCategories(),fetchHomepageAssistanceFee(),fetchJobAssistanceFee(),fetchScholarshipAssistanceFee(),fetchRechargeBillAssistanceFee()]);setServices(ss);setCategories(cc);setHomepageFee(Number(h.price_inr));setJobFee(Number(j.price_inr??30));setScholarshipFee(Number(s.price_inr??30));setRechargeFee(Number(r.price_inr??10));const values=Array.from(new Set(ss.map((x:any)=>Number(x.price_inr||0))));if(values.length===1){setGlobalFee(values[0] as number);if(editing===null)setPrice(values[0] as number)}}catch{setError('Unable to load services, pricing, or categories.')}}
 useEffect(()=>{load()},[])
 const currentFeeText=useMemo(()=>{const v=Array.from(new Set(services.map(x=>Number(x.price_inr||0)))).sort((a,b)=>a-b);return !v.length?'No services':v.length===1?`₹${v[0]}`:`Different fees: ₹${v.join(', ₹')}`},[services])
 const normalizedSearch=searchQuery.trim().toLowerCase();const filteredServices=useMemo(()=>!normalizedSearch?services:services.filter(x=>[x.name,x.catalog_name,x.description,x.category,x.keywords].filter(Boolean).join(' ').toLowerCase().includes(normalizedSearch)),[services,normalizedSearch])
 const reset=()=>{setName('');setDesc('');setKeywords('');setCategoryId('');setPrice(globalFee===''?0:Number(globalFee));setOfficialStatus('unconfirmed');setOfficialFee('');setEditing(null)}
 const save=async()=>{try{setBusy(true);setError('');setMessage('');if(price<0){setError('Assistance fee cannot be negative.');return}if(officialStatus==='known'&&(officialFee===''||Number(officialFee)<0)){setError('Enter the confirmed official fee.');return}const payload={name,description:desc,keywords,category_id:categoryId?Number(categoryId):null,price_inr:price,official_fee_status:officialStatus,official_fee_inr:officialStatus==='known'?Number(officialFee):officialStatus==='none'?0:null};if(editing)await updateService(editing,payload);else await createService(payload);setMessage(editing?'Service updated successfully.':'Service added successfully.');reset();await load()}catch(err:any){setError(typeof err?.response?.data?.error==='string'?err.response.data.error:'Unable to save service.')}finally{setBusy(false)}}
 const saveSpecialFee=async(kind:'job'|'scholarship'|'recharge')=>{const state=kind==='job'?jobFee:kind==='scholarship'?scholarshipFee:rechargeFee;const value=Number(state);if(state===''||!Number.isFinite(value)||value<0||value>100000){setError('Enter a valid assistance fee from ₹0 to ₹1,00,000.');return}try{setBusy(true);setError('');setMessage('');const result=kind==='job'?await updateJobAssistanceFee(value):kind==='scholarship'?await updateScholarshipAssistanceFee(value):await updateRechargeBillAssistanceFee(value);if(kind==='job')setJobFee(Number(result.price_inr));else if(kind==='scholarship')setScholarshipFee(Number(result.price_inr));else setRechargeFee(Number(result.price_inr));setMessage(`${result.message} Existing submitted requests keep their original agreed fee.`)}catch(err:any){setError(err?.response?.data?.error||'Unable to update the assistance fee.')}finally{setBusy(false)}}
 const updateWebsiteFee=async()=>{const value=Number(globalFee);if(globalFee===''||!Number.isFinite(value)||value<0){setError('Enter a valid assistance fee.');return}if(!globalConfirmed){setError('Confirm that you understand this changes all current service fees.');return}if(!window.confirm(`Change the assistance fee for all ${services.length} services to ₹${value}? Existing submitted requests will keep their original fee.`))return;try{setBusy(true);const result=await updateAllAssistanceFees(value);setMessage(`${result.message} Existing submitted requests were not repriced.`);setGlobalConfirmed(false);await load()}catch(err:any){setError(err?.response?.data?.error||'Unable to update the website-wide assistance fee.')}finally{setBusy(false)}}
 const saveHomepageFee=async()=>{const value=Number(homepageFee);if(homepageFee===''||!Number.isFinite(value)||value<0){setError('Enter a valid homepage assistance fee.');return}try{setBusy(true);const result=await updateHomepageAssistanceFee(value);setMessage(`${result.message} Individual service fees were not changed.`)}catch(err:any){setError(err?.response?.data?.error||'Unable to update the homepage assistance fee.')}finally{setBusy(false)}}
 const searchCatalog=async()=>{const q=searchQuery.trim();if(!q){setJobResults([]);return}try{setSearching(true);const result=await fetchAdminJobs({q,per_page:100});setJobResults(result.items||[])}catch(err:any){setError(err?.response?.data?.error||'Unable to search job notices. Service search is still available.')}finally{setSearching(false)}}
 const addCategory=async()=>{const value=newCategory.trim();if(value.length<2)return;try{setBusy(true);const result=await createCategory(value);setNewCategory('');await load();if(result.category?.id)setCategoryId(String(result.category.id));setMessage('Category added successfully.')}catch(err:any){setError(err?.response?.data?.error||'Unable to add category.')}finally{setBusy(false)}}
 const edit=(x:any)=>{setEditing(x.id);setName(x.catalog_name||x.name);setDesc(x.description||'');setKeywords(x.keywords||'');setCategoryId(x.category_id?String(x.category_id):'');setPrice(x.price_inr??0);setOfficialStatus(x.official_fee_status||'unconfirmed');setOfficialFee(x.official_fee_inr??'');window.scrollTo({top:0,behavior:'smooth'})}
 const toggle=async(x:any)=>{try{await setServiceActive(x.id,!x.is_active);setMessage(`Service ${x.is_active?'disabled':'enabled'} successfully.`);await load()}catch{setError('Unable to update service availability.')}}
 const FeeCard=({id,title,value,setValue,onSave,help}:{id:string,title:string,value:number|'',setValue:(v:number|'')=>void,onSave:()=>void,help:string})=><section className="dashboard-section global-fee-card" aria-labelledby={id}><div><span className="eyebrow">Website-wide pricing</span><h3 id={id}>{title}</h3><p className="global-fee-current">{help}</p></div><div className="global-fee-controls"><label>{title} (₹)<input type="number" min="0" max="100000" step="0.01" value={value} onChange={e=>setValue(e.target.value===''?'':Number(e.target.value))}/></label><button type="button" disabled={busy||value===''} onClick={onSave}>{busy?'Saving…':'Save fee'}</button><small>₹0 is allowed. Changes apply to future requests; existing submitted requests keep their agreed fee.</small></div></section>
 return <div><div className="section-header"><div><h2>Services & fees</h2></div></div>{error&&<p className="info" role="alert">{error}</p>}{message&&<p className="success-message" role="status">{message}</p>}
 <section className="dashboard-section global-fee-card"><div><span className="eyebrow">Homepage pricing display</span><h3>Homepage Applicable Assistance Fee</h3></div><div className="global-fee-controls"><label>Applicable Assistance Fee (₹)<input type="number" min="0" max="100000" step="0.01" value={homepageFee} onChange={e=>setHomepageFee(e.target.value===''?'':Number(e.target.value))}/></label><button disabled={busy||homepageFee===''} onClick={saveHomepageFee}>Save homepage fee</button></div></section>
 <section className="dashboard-section global-fee-card"><div><span className="eyebrow">Website-wide pricing</span><h3>All service fees</h3><p><strong>Current catalog:</strong> {currentFeeText}</p></div><div className="global-fee-controls"><label>Applicable Assistance Fee (₹)<input type="number" min="0" max="100000" step="0.01" value={globalFee} onChange={e=>setGlobalFee(e.target.value===''?'':Number(e.target.value))}/></label><label className="fee-acknowledgement"><input type="checkbox" checked={globalConfirmed} onChange={e=>setGlobalConfirmed(e.target.checked)}/> I understand this replaces the current assistance fee on every service. Existing submitted requests keep their original agreed fee.</label><button disabled={busy||!globalConfirmed||globalFee===''} onClick={updateWebsiteFee}>Update fee across website</button></div></section>
 <FeeCard id="job-global-fee-title" title="Job Application Assistance Fee" value={jobFee} setValue={setJobFee} onSave={()=>saveSpecialFee('job')} help="Applies to every new official job application assistance request."/>
 <FeeCard id="scholarship-global-fee-title" title="Scholarship Application Assistance Fee" value={scholarshipFee} setValue={setScholarshipFee} onSave={()=>saveSpecialFee('scholarship')} help="Scholarship requests remain assistance-only; no official-fee option is added."/>
 <FeeCard id="recharge-global-fee-title" title="Recharge & Bill Payments Assistance Fee" value={rechargeFee} setValue={setRechargeFee} onSave={()=>saveSpecialFee('recharge')} help="Default ₹10. Applies to future Mobile Recharge and supported bill-payment assistance requests. Recharge/bill principal is kept separate from this assistance charge."/>
 <section className="dashboard-section"><h3>Search any service or job</h3><div className="admin-filters"><label>Service or job<input value={searchQuery} onChange={e=>{setSearchQuery(e.target.value);if(!e.target.value.trim())setJobResults([])}} onKeyDown={e=>{if(e.key==='Enter')searchCatalog()}} placeholder="Search service, recharge, bill payment, job, organization, category or keyword"/></label><button disabled={searching} onClick={searchCatalog}>{searching?'Searching…':'Search services & jobs'}</button>{searchQuery&&<button className="btn-secondary" onClick={()=>{setSearchQuery('');setJobResults([])}}>Clear</button>}</div>{normalizedSearch&&<div className="service-info-grid"><article><h3>Services ({filteredServices.length})</h3>{filteredServices.length?<ul className="admin-service-list">{filteredServices.slice(0,30).map(x=><li key={x.id}><div><strong>{x.name}</strong><small>{x.category||'Uncategorized'} · ₹{Number(x.price_inr||0).toFixed(2)}</small></div><button onClick={()=>edit(x)}>Edit service</button></li>)}</ul>:<p>No matching services.</p>}</article><article><h3>Jobs ({jobResults.length})</h3>{jobResults.length?<ul className="admin-service-list">{jobResults.slice(0,30).map(j=><li key={j.id}><div><strong>{j.title}</strong><small>{j.organization}</small></div><Link className="btn btn-secondary" to={`/admin/jobs?q=${encodeURIComponent(searchQuery.trim())}`}>Edit job</Link></li>)}</ul>:<p>Press Search to find matching job notices.</p>}</article></div>}</section>
 <div className="dashboard-section admin-form service-admin-form"><label>Service name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Description<textarea rows={4} value={desc} onChange={e=>setDesc(e.target.value)}/></label><label>Category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="inline-admin-field"><label>New category<input value={newCategory} onChange={e=>setNewCategory(e.target.value)}/></label><button disabled={busy||newCategory.trim().length<2} onClick={addCategory}>Add category</button></div><label>Search keywords<input value={keywords} onChange={e=>setKeywords(e.target.value)}/></label><label>Assistance fee (₹)<input type="number" min="0" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><label>Official fee status<select value={officialStatus} onChange={e=>setOfficialStatus(e.target.value as OfficialStatus)}><option value="unconfirmed">Not confirmed</option><option value="known">Known</option><option value="none">No official fee</option></select></label>{officialStatus==='known'&&<label>Official fee (₹)<input type="number" min="0" value={officialFee} onChange={e=>setOfficialFee(e.target.value===''?'':Number(e.target.value))}/></label>}<div className="cta-row"><button disabled={busy||!name.trim()} onClick={save}>{editing?'Save changes':'Add service'}</button>{editing&&<button className="btn-secondary" onClick={reset}>Cancel</button>}</div></div>
 <div className="admin-service-list">{filteredServices.map(x=><article key={x.id} className="dashboard-section"><div className="section-header inline"><div><h3>{x.name}</h3><p>{x.category||'Uncategorized'}</p></div><span className={`status-badge ${x.is_active?'completed':'cancelled'}`}>{x.is_active?'Active':'Disabled'}</span></div><p>{x.description}</p><FeeSummary data={x}/><div className="cta-row"><button onClick={()=>edit(x)}>Edit</button><button className="btn-secondary" onClick={()=>toggle(x)}>{x.is_active?'Disable':'Enable'}</button></div></article>)}</div></div>
}
