import React,{useEffect,useState} from 'react'
import {Link,useLocation} from 'react-router-dom'
import {PROVIDER} from '../services/config'
import {fetchServiceCatalog,readCachedServices,servicePath} from '../services/serviceCatalog'

const CATEGORY_ROUTES:Record<string,{title:string;query:string}>={
 jobs:{title:'Government Jobs',query:'jobs'},scholarships:{title:'Scholarships',query:'scholarship'},meeseva:{title:'MeeSeva / Public Services',query:'meeseva'},certificates:{title:'MeeSeva Certificates',query:'certificate'},schemes:{title:'Government Schemes',query:'scheme'},
}
function matches(service:any,query:string){const hay=`${service?.name||''} ${service?.category||''} ${service?.keywords||''} ${service?.description||''}`.toLowerCase();if(query==='certificate')return /certificate|birth|death|income|caste|community|residence|domicile|nativity|marriage/.test(hay);if(query==='meeseva')return /meeseva|certificate|public service/.test(hay);if(query==='scheme')return /scheme|welfare|benefit|pension/.test(hay);return hay.includes(query)}
export default function Category(){
 const location=useLocation();const slug=location.pathname.replace(/^\/+|\/+$/g,'').toLowerCase();const category=CATEGORY_ROUTES[slug]||{title:'Public Services',query:slug};const cached=readCachedServices(true);const [services,setServices]=useState<any[]>(()=>cached.filter(s=>matches(s,category.query)));const [loading,setLoading]=useState(cached.length===0);const [error,setError]=useState('');const [retry,setRetry]=useState(0)
 useEffect(()=>{let active=true;setError('');if(!services.length)setLoading(true);fetchServiceCatalog(retry>0).then(items=>{if(active){setServices(items.filter(s=>matches(s,category.query)));setError('')}}).catch(()=>{if(active&&!services.length)setError('Unable to load services right now. Please try again.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[category.query,retry])
 return <div className="category-page"><div className="form-hero"><span className="eyebrow">Services</span><h1>{category.title}</h1></div><div className="section-header inline"><div><h2>Available services</h2></div><span className="search-meta">{services.length}</span></div>{services.length>0?<ul className="service-list">{services.map(s=><li key={s.id} className="service-card"><div className="service-card-top"><span className="service-badge">{s.category||category.title}</span><span className="service-price">Applicable Assistance Fee ₹{s.price_inr}</span></div><h3><Link to={servicePath(s)}>{s.name}</Link></h3><Link className="text-link" to={servicePath(s)}>View & apply</Link></li>)}</ul>:loading?<div className="empty-state" role="status">Loading services…</div>:error?<div className="empty-state"><p className="info" role="alert">{error}</p><button className="btn btn-primary" type="button" onClick={()=>setRetry(value=>value+1)}>Try again</button></div>:<div className="empty-state"><h2>No services found</h2><Link className="btn btn-primary" to="/government-services">Browse all services</Link></div>}<p className="provider-note">Need help? <a href={`tel:${PROVIDER.phone}`}>{PROVIDER.phone}</a></p></div>
}
