import React,{useState} from 'react'
import {Link} from 'react-router-dom'
import {PROVIDER} from '../services/config'

export default function Contact(){
 const [form,setForm]=useState({name:'',email:'',phone:'',message:''});const [msg,setMsg]=useState('')
 const submit=(e:React.FormEvent)=>{e.preventDefault();setMsg('Thank you. Your message has been received. We will contact you soon.');setForm({name:'',email:'',phone:'',message:''})}
 return <div className="form-page"><div className="form-hero"><span className="eyebrow">We’re here to help</span><h1>Contact us</h1><p>Have a question about a service or your request? Send us a message or use the provider contact details below.</p></div><div className="contact-grid"><section className="dashboard-section contact-card"><span className="eyebrow">Provider</span><h2>{PROVIDER.name}</h2><div className="contact-details"><a href={`tel:${PROVIDER.phone}`}>{PROVIDER.phone}</a> · <a href={`tel:${PROVIDER.phone2}`}>{PROVIDER.phone2}</a> · <a href={`mailto:${PROVIDER.email}`}>{PROVIDER.email}</a></div><p>For request-specific help, you can also submit a grievance from your client workspace.</p><Link className="btn btn-secondary" to="/submit-grievance">Submit a grievance</Link></section><section className="form-card"><form onSubmit={submit} className="request-form"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Message<textarea required minLength={10} rows={6} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label>{msg&&<p className="success-message" role="status">{msg}</p>}<button type="submit">Send message</button></form></section></div></div>
}
