import {Link} from 'react-router-dom'
import {PROVIDER} from '../services/config'
import {buildWhatsAppUrl,currentPageUrl} from '../services/whatsapp'

export default function Contact(){
 const subject=encodeURIComponent('Public Online Service Provider enquiry')
 const whatsappUrl=buildWhatsAppUrl({topic:'General enquiry',pageUrl:currentPageUrl()})
 return <div className="form-page"><div className="form-hero"><span className="eyebrow">We’re here to help</span><h1>Contact us</h1><p>Have a question about a service or your request? Use the verified provider contact options below.</p></div><div className="contact-grid"><section className="dashboard-section contact-card"><span className="eyebrow">Provider</span><address className="contact-address"><strong>{PROVIDER.name}</strong><a href={`tel:${PROVIDER.phone}`}>{PROVIDER.phone}</a><a href={`tel:${PROVIDER.phone2}`}>{PROVIDER.phone2}</a><a href={`mailto:${PROVIDER.email}?subject=${subject}`}>{PROVIDER.email}</a><a href={whatsappUrl} target="_blank" rel="noopener noreferrer">WhatsApp: +91 {PROVIDER.phone}</a></address><p>For request-specific help, submit a private grievance from your client workspace so it remains linked to your application.</p><Link className="btn btn-secondary" to="/submit-grievance">Submit a grievance</Link></section><section className="form-card contact-card"><span className="eyebrow">General enquiries</span><h2>Message the provider</h2><p>Use WhatsApp for quick service questions or open your email app for a general enquiry. Include your request ID if your message concerns an existing application, but never send passwords, OTPs, PINs, CVV details or banking credentials.</p><div className="cta-row"><a className="btn btn-whatsapp" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Chat on WhatsApp</a><a className="btn btn-primary" href={`mailto:${PROVIDER.email}?subject=${subject}`}>Compose email</a></div><p className="auth-hint">For urgent help, call either verified phone number shown here.</p></section></div></div>
}
