import React,{useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import SearchPanel from '../components/ui/SearchPanel'
import {fetchJobs,JobNotification,jobPath,formatJobDate} from '../services/jobs'
import {fetchServiceCatalog,isHomepageHighlightEligible,readCachedServices,servicePath,slugifyServiceName} from '../services/serviceCatalog'
import {fetchScholarships,Scholarship,scholarshipPath} from '../services/scholarships'
import '../styles/home-modern.css'
import '../styles/home-final-alignment.css'

const serviceTerms=['bank account seeding','dbt assistance','caste','income','residence','aadhaar','pan','voter','ration','birth','death','driving','vehicle','passport','land','meeseva','education','legal','health','welfare','labour']
const paymentTerms=['recharge','bill payment','electricity','dth','broadband','water bill','gas bill','fastag']
function paymentDisplayName(value:string){return String(value||'').replace(/^\s*(?:apply(?:\s+for)?|application(?:\s+for)?|request(?:\s+for)?|pay)\s+/i,'').trim()}
function short(value?:string|null,fallback='See details'){const text=String(value||'').trim();return text||fallback}

export default function Home(){
 const [catalog,setCatalog]=useState<any[]>(()=>readCachedServices(true)),[jobs,setJobs]=useState<JobNotification[]>([]),[scholarships,setScholarships]=useState<Scholarship[]>([])
 useEffect(()=>{let a=true;fetchServiceCatalog().then(x=>{if(a)setCatalog(x)}).catch(()=>{});return()=>{a=false}},[])
 useEffect(()=>{let a=true;fetchJobs({limit:8}).then(x=>{if(a)setJobs((x.items||[]).slice(0,3))}).catch(()=>{});return()=>{a=false}},[])
 useEffect(()=>{let a=true;fetchScholarships().then(x=>{if(a)setScholarships((x.items||[]).slice(0,3))}).catch(()=>{});return()=>{a=false}},[])
 useEffect(()=>{const preload=()=>{import('./ServiceDetail');import('./ServiceDirectory');import('./RechargeBillRequest');import('./Login');import('./Jobs');import('./Scholarships')};const idle=(window as any).requestIdleCallback;const h=idle?idle(preload,{timeout:2500}):window.setTimeout(preload,1200);return()=>idle?(window as any).cancelIdleCallback?.(h):window.clearTimeout(h)},[])
 const browse=useMemo(()=>{const eligible=catalog.filter(isHomepageHighlightEligible).filter(s=>!`${s.name} ${s.keywords||''}`.toLowerCase().includes('fraud complaint')),out:any[]=[];serviceTerms.forEach(t=>{const m=eligible.find(s=>!out.includes(s)&&`${s.name} ${s.category||''} ${s.keywords||''}`.toLowerCase().includes(t));if(m)out.push(m)});eligible.forEach(s=>{if(out.length<18&&!out.includes(s))out.push(s)});return out.slice(0,18)},[catalog])
 const payments=useMemo(()=>catalog.filter(s=>paymentTerms.some(t=>`${s.name} ${s.category||''} ${s.keywords||''}`.toLowerCase().includes(t))).slice(0,6),[catalog])
 const icon=(name:string)=>{const n=name.toLowerCase();if(n.includes('seeding')||n.includes('dbt'))return'↔';if(n.includes('aadhaar'))return'◎';if(n.includes('vehicle')||n.includes('driving'))return'▰';if(n.includes('passport')||n.includes('pan')||n.includes('voter'))return'▣';if(n.includes('land'))return'⌂';if(n.includes('health'))return'♥';if(n.includes('education'))return'◆';return'▤'}
 const paymentPath=(service:any)=>`/recharge-bills/${encodeURIComponent(service.slug||slugifyServiceName(service.name))}`
 return <div className="world-home">
  <section className="world-hero"><div className="world-hero-copy"><span className="world-kicker">SIMPLE · SECURE · TRUSTED</span><h1>All Your Online Services <em>in One Place</em></h1><p>Access government services, discover jobs and scholarships, pay bills, and get clear application support.</p><SearchPanel variant="hero"/><div className="popular-row"><span>Popular:</span><Link to="/certificates">PAN & Certificates</Link><Link to="/jobs">Government Jobs</Link><Link to="/scholarships">Scholarships</Link><Link to="/recharge-bills">Electricity Bill</Link></div></div><aside className="world-hero-side"><div className="hero-promise"><b>▤ Government Services</b><span>Clear application assistance</span></div><div className="hero-promise"><b>▣ Jobs & Careers</b><span>Verified notices and eligibility</span></div><div className="hero-promise"><b>◆ Scholarships</b><span>Eligibility before application</span></div><div className="hero-promise"><b>₹ Bill Payments</b><span>Recharge and utility payments</span></div></aside></section>
  <section className="world-primary" aria-label="Main actions"><Link to="/government-services"><i>▤</i><div><h2>Government Services</h2><p>Browse available application assistance</p></div><b>›</b></Link><Link to="/jobs"><i>▣</i><div><h2>Jobs</h2><p>Verified notifications with eligibility details</p></div><b>›</b></Link><Link to="/scholarships"><i>◆</i><div><h2>Scholarships</h2><p>Check eligibility before you apply</p></div><b>›</b></Link><Link to="/recharge-bills"><i>₹</i><div><h2>Recharge & Bill Payments</h2><p>Mobile, DTH, electricity and more</p></div><b>›</b></Link></section>
  <section className="world-section service-browser" id="browse-services"><header><div><h2>Browse Government Services</h2><p>Frequently needed services arranged for quick access.</p></div><Link to="/government-services">View All Services →</Link></header><div className="service-icon-grid">{browse.map(s=><Link key={s.id} to={servicePath(s)}><i>{icon(s.name)}</i><span>{s.name}</span></Link>)}</div></section>
  <section className="opportunity-band jobs-opportunity"><div className="opportunity-intro"><span className="opportunity-kicker">Latest Opportunities</span><h2>Government & Private Jobs</h2><p>Current verified job notifications with qualification, age/eligibility information, important dates and official-source details before you apply.</p><Link className="opportunity-action" to="/jobs">View All Jobs →</Link></div><div className="opportunity-cards">{jobs.length?jobs.map(job=><Link className="opportunity-card" key={job.id} to={jobPath(job)}><div className="opportunity-card-title"><i>▣</i><div><b>{job.title}</b><span>{job.organization}</span></div></div><dl><div><dt>Eligibility</dt><dd>{short(job.qualification)}</dd></div><div><dt>Age</dt><dd>{short(job.age_limit)}</dd></div><div><dt>Last date</dt><dd>{formatJobDate(job.deadline)}</dd></div></dl><strong>View eligibility & apply →</strong></Link>):<p>Verified job notifications are loading…</p>}</div></section>
  <section className="opportunity-band scholarship-opportunity"><div className="opportunity-intro"><span className="opportunity-kicker">Education for a Better Tomorrow</span><h2>Scholarships</h2><p>Active scholarship opportunities with client-friendly eligibility, study level, income/category conditions, deadlines and source details before application assistance.</p><Link className="opportunity-action" to="/scholarships">View All Scholarships →</Link></div><div className="opportunity-cards">{scholarships.length?scholarships.map(s=><Link className="opportunity-card" key={s.id} to={scholarshipPath(s)}><div className="opportunity-card-title"><i>◆</i><div><b>{s.title}</b><span>{s.provider}</span></div></div><dl><div><dt>Eligibility</dt><dd>{short(s.eligibility,s.education_level||'Open details to check')}</dd></div>{s.income_limit&&<div><dt>Income limit</dt><dd>{s.income_limit}</dd></div>}<div><dt>Last date</dt><dd>{s.deadline?new Date(`${s.deadline}T00:00:00`).toLocaleDateString('en-IN'):'See listing'}</dd></div></dl><strong>Check eligibility & apply →</strong></Link>):<p>Active scholarships are loading…</p>}</div></section>
  <section className="opportunity-band payments-opportunity"><div className="opportunity-intro"><span className="opportunity-kicker">Fast · Secure · Convenient</span><h2>Recharge & Bill Payments</h2><p>Pay mobile, DTH, electricity, water, gas and other supported bills through a clear guided flow.</p><Link className="opportunity-action payment-action" to="/recharge-bills">Pay Now →</Link></div><div className="payment-showcase">{payments.length?payments.map(s=><Link key={s.id} to={paymentPath(s)}><i>₹</i><span>{paymentDisplayName(s.name)}</span></Link>):<><Link to="/recharge-bills"><i>▣</i><span>Mobile Recharge</span></Link><Link to="/recharge-bills"><i>◉</i><span>DTH Recharge</span></Link><Link to="/recharge-bills"><i>⚡</i><span>Electricity Bill</span></Link><Link to="/recharge-bills"><i>◈</i><span>Water Bill</span></Link></>}</div></section>
  <section className="trust-strip"><div><b>✓</b><span><strong>Trusted & Secure</strong>Your data is handled carefully</span></div><div><b>◎</b><span><strong>Support & Guidance</strong>Clear help when needed</span></div><div><b>▦</b><span><strong>Wide Range of Services</strong>Services and opportunities together</span></div><div><b>♥</b><span><strong>For a Digital India</strong>Simple access to online services</span></div></section>
  <section className="world-cta"><div><span>NEED HELP WITH ANY SERVICE?</span><h2>We are here to support you.</h2><p>Public Online Service Provider is an independent private assistance platform, not a government portal.</p></div><Link to="/contact">Contact Us →</Link></section>
 </div>
}
