import React,{useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import SearchPanel from '../components/ui/SearchPanel'
import LatestJobs from '../components/jobs/LatestJobs'
import {fetchServiceCatalog,isHomepageHighlightEligible,readCachedServices,servicePath} from '../services/serviceCatalog'
import {fetchScholarships,Scholarship,scholarshipPath} from '../services/scholarships'
import axios from 'axios'
import {apiBase} from '../services/apiBase'
import '../styles/home-modern.css'

const serviceTerms=['caste','income','residence','aadhaar','pan','voter','ration','birth','death','driving','vehicle','passport','land','meeseva','education','legal','health','welfare','labour']
const paymentTerms=['recharge','bill payment','electricity','dth','broadband','water bill','gas bill','fastag']

export default function Home(){
 const [catalog,setCatalog]=useState<any[]>(()=>readCachedServices(true));const [scholarships,setScholarships]=useState<Scholarship[]>([])
 useEffect(()=>{let a=true;fetchServiceCatalog().then(x=>{if(a)setCatalog(x)}).catch(()=>{});return()=>{a=false}},[])
 useEffect(()=>{let a=true;fetchScholarships().then(x=>{if(a)setScholarships((x.items||[]).slice(0,5))}).catch(()=>{});return()=>{a=false}},[])
 useEffect(()=>{const preload=()=>{import('./ServiceDetail');import('./Login');import('./Jobs');import('./Scholarships')};const idle=(window as any).requestIdleCallback;const h=idle?idle(preload,{timeout:2500}):window.setTimeout(preload,1200);return()=>idle?(window as any).cancelIdleCallback?.(h):window.clearTimeout(h)},[])
 const browse=useMemo(()=>{const eligible=catalog.filter(isHomepageHighlightEligible),out:any[]=[];serviceTerms.forEach(t=>{const m=eligible.find(s=>!out.includes(s)&&`${s.name} ${s.category||''} ${s.keywords||''}`.toLowerCase().includes(t));if(m)out.push(m)});eligible.forEach(s=>{if(out.length<18&&!out.includes(s))out.push(s)});return out.slice(0,18)},[catalog])
 const payments=useMemo(()=>catalog.filter(s=>paymentTerms.some(t=>`${s.name} ${s.category||''} ${s.keywords||''}`.toLowerCase().includes(t))).slice(0,8),[catalog])
 const icon=(name:string)=>{const n=name.toLowerCase();if(n.includes('aadhaar'))return'◎';if(n.includes('vehicle')||n.includes('driving'))return'▰';if(n.includes('passport')||n.includes('pan')||n.includes('voter'))return'▣';if(n.includes('land'))return'⌂';if(n.includes('health'))return'♥';if(n.includes('education'))return'◆';return'▤'}
 return <div className="world-home">
  <section className="world-hero"><div className="world-hero-copy"><span className="world-kicker">GOVERNMENT SERVICES · JOBS · SCHOLARSHIPS · PAYMENTS · ALL IN ONE PLACE</span><h1>A Simpler Way to a <em>Brighter Tomorrow</em></h1><p>Access essential services, discover opportunities, pay bills and get clear support from one trusted platform.</p><SearchPanel variant="hero"/><div className="popular-row"><span>Popular:</span><Link to="/#browse-services">Certificates</Link><Link to="/jobs">Jobs</Link><Link to="/scholarships">Scholarships</Link><Link to="/#payments">Recharge & Bills</Link></div></div><aside className="world-hero-side"><div className="hero-promise"><b>⚡ Fast & Convenient</b><span>Save time, do more online</span></div><div className="hero-promise"><b>✓ Trusted & Secure</b><span>Clear steps and safer guidance</span></div><div className="hero-promise"><b>◆ Expert Support</b><span>Help when you need it</span></div><div className="hero-promise"><b>♥ Opportunities for All</b><span>Jobs, scholarships and more</span></div></aside></section>
  <section className="world-primary" aria-label="Main actions"><Link to="/#browse-services"><i>▤</i><div><h2>Apply for Government Services</h2><p>Certificates, applications and more</p></div><b>›</b></Link><Link to="/jobs"><i>▣</i><div><h2>Find Government Jobs</h2><p>Latest notifications and opportunities</p></div><b>›</b></Link><Link to="/scholarships"><i>◆</i><div><h2>Explore Scholarships</h2><p>For students and aspirants</p></div><b>›</b></Link><Link to="/#payments"><i>₹</i><div><h2>Recharge & Pay Bills</h2><p>Mobile, DTH, utilities and more</p></div><b>›</b></Link></section>
  <section className="world-section service-browser" id="browse-services"><header><div><h2>Browse Government Services</h2><p>Frequently needed services, arranged together for quick access.</p></div><Link to="/#service-search">View All Services →</Link></header><div className="service-icon-grid">{browse.map(s=><Link key={s.id} to={servicePath(s)}><i>{icon(s.name)}</i><span>{s.name}</span></Link>)}</div></section>
  <section className="world-information-grid"><div className="world-panel jobs-panel"><header><h2>Latest Job Notifications</h2><Link to="/jobs">View All Jobs →</Link></header><LatestJobs/></div><div className="world-panel scholarship-panel"><header><h2>Latest Scholarships</h2><Link to="/scholarships">View All Scholarships →</Link></header><div className="compact-list">{scholarships.length?scholarships.map(s=><Link key={s.id} to={scholarshipPath(s)}><i>◆</i><div><b>{s.title}</b><span>{s.provider}</span></div><strong>Open</strong></Link>):<p>Scholarships are loading…</p>}</div></div><div className="world-panel payments-panel" id="payments"><header><h2>Recharge & Bill Payments</h2><Link to="/#service-search">View All →</Link></header><div className="payment-grid">{payments.length?payments.map(s=><Link key={s.id} to={servicePath(s)}><i>₹</i><span>{s.name}</span></Link>):<><Link to="/#service-search"><i>▣</i><span>Mobile Recharge</span></Link><Link to="/#service-search"><i>⚡</i><span>Electricity Bill</span></Link><Link to="/#service-search"><i>◉</i><span>DTH Recharge</span></Link><Link to="/#service-search"><i>▤</i><span>Other Bills</span></Link></>}</div><div className="support-card"><i>☏</i><div><b>Need Help?</b><span>Our support team is here for you.</span></div><Link to="/contact">Contact Support →</Link></div></div></section>
  <section className="trust-strip"><div><b>✓</b><span><strong>Secure & Trusted</strong>Your data, our priority</span></div><div><b>⚡</b><span><strong>Fast & Convenient</strong>Save time online</span></div><div><b>◎</b><span><strong>Easy to Use</strong>Clear on mobile and desktop</span></div><div><b>♥</b><span><strong>Here to Help</strong>Support when you need it</span></div></section>
  <section className="world-cta"><div><span>BETTER OPPORTUNITIES</span><h2>A clearer path to services and a brighter future.</h2><p>Learn · Apply · Track · Grow</p></div><Link to="/#service-search">Explore Now →</Link></section>
 </div>
}
