import React,{useEffect,useMemo,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import Seo,{SITE} from '../components/ui/Seo'
import {fetchJob,formatJobDate,JobNotification} from '../services/jobs'

const field=(value?:string|null)=>value||'Not provided in the source listing — see the official notice.'

export default function JobDetail(){
  const {slug=''}=useParams();const [job,setJob]=useState<JobNotification|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  useEffect(()=>{let active=true;setLoading(true);fetchJob(slug).then(data=>{if(active)setJob(data.job)}).catch(()=>{if(active)setError('This published job notice is unavailable or has closed.')} ).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[slug])
  const schema=useMemo(()=>job?{'@context':'https://schema.org','@type':'WebPage',name:`${job.title} — ${job.organization}`,url:`${SITE.url}/jobs/${job.slug}`,description:job.summary||`Official-source recruitment notice from ${job.organization}.`,isPartOf:{'@type':'WebSite',name:SITE.name,url:SITE.url}}:undefined,[job])
  if(loading)return <div className="dashboard-state"><div className="loading-dot"/><p>Loading job notice…</p></div>
  if(error||!job)return <div className="dashboard-state error-state"><h1>Job notice unavailable</h1><p>{error}</p><Link className="btn btn-primary" to="/jobs">View current jobs</Link></div>
  const applyUrl=job.application_url||job.official_notice_url
  const assistancePath=`/services/apply-government-job?job=${encodeURIComponent(job.slug)}`
  return <article className="job-detail-page"><Seo title={`${job.title} — ${job.organization}`} description={job.summary||`Review the official-source recruitment notice from ${job.organization}.`} path={`/jobs/${job.slug}`} schema={schema}/><nav className="breadcrumbs" aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span><Link to="/jobs">Jobs</Link><span>/</span><span>{job.title}</span></nav><header className="job-detail-header"><div><div className="job-label-row"><span className={`job-type-badge ${job.job_type}`}>{job.job_type}</span>{job.is_featured&&<span className="job-featured">Highlighted</span>}</div><h1>{job.title}</h1><p>{job.organization}</p>{job.location&&<small>{job.location}{job.appointment_type?` · ${job.appointment_type}`:''}</small>}</div><div className="job-detail-deadline"><span>Last date</span><strong>{formatJobDate(job.deadline)}</strong><Link className="btn btn-primary" to={assistancePath}>Apply with assistance — ₹30</Link><small>₹30 assistance fee + official application fee, if applicable.</small><a className="text-link" href={applyUrl} target="_blank" rel="noopener noreferrer">Apply directly on official website ↗</a></div></header><div className="job-detail-grid"><section className="dashboard-section"><h2>Notice details</h2><dl className="job-detail-facts"><div><dt>Qualification</dt><dd>{field(job.qualification)}</dd></div><div><dt>Age limit</dt><dd>{field(job.age_limit)}</dd></div><div><dt>Official application fee</dt><dd>{field(job.application_fee)}</dd></div><div><dt>Vacancies</dt><dd>{field(job.vacancies)}</dd></div><div><dt>Salary</dt><dd>{field(job.salary)}</dd></div><div><dt>Application starts</dt><dd>{formatJobDate(job.application_start_date)}</dd></div></dl>{job.summary&&<><h2>Summary</h2><p>{job.summary}</p></>}</section><aside className="official-notice-card"><span className="verified-source">✓ Official source checked</span><h2>Confirm before applying</h2><p>Read the complete official notice for eligibility, reservation rules, documents, fees and deadlines. Clients must enter OTPs, payment PINs and passwords themselves only on the official portal.</p><a href={job.official_notice_url} target="_blank" rel="noopener noreferrer">View official notification ↗</a>{job.source&&<small>Source: {job.source.name}</small>}</aside></div></article>
}
