import React,{FormEvent,useEffect,useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {fetchJobs,fetchJobSources,JobNotification,JobSource} from '../services/jobs'
import JobCard from '../components/jobs/JobCard'

export default function Jobs(){
  const [params,setParams]=useSearchParams();const initialQuery=params.get('q')||'';const initialType=['government','private'].includes(params.get('type')||'')?(params.get('type')||''):''
  const [jobs,setJobs]=useState<JobNotification[]>([]);const [sources,setSources]=useState<JobSource[]>([]);const [query,setQuery]=useState(initialQuery);const [submitted,setSubmitted]=useState(initialQuery);const [type,setTypeState]=useState(initialType);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const load=()=>{setLoading(true);setError('');fetchJobs({limit:100,...(submitted?{q:submitted}:{}),...(type?{type}:{})}).then(data=>setJobs(data.items||[])).catch(()=>setError('We could not load the verified job feed. Please try again.')).finally(()=>setLoading(false))}
  useEffect(load,[submitted,type])
  useEffect(()=>{fetchJobSources().then(data=>setSources(data.items||[])).catch(()=>{})},[])
  const updateLocation=(nextQuery:string,nextType:string)=>{const next=new URLSearchParams();if(nextQuery)next.set('q',nextQuery);if(nextType)next.set('type',nextType);setParams(next,{replace:true})}
  const submit=(event:FormEvent)=>{event.preventDefault();const next=query.trim();setSubmitted(next);updateLocation(next,type)}
  const setType=(next:string)=>{setTypeState(next);updateLocation(submitted,next)}
  return <div className="jobs-page"><section className="jobs-hero"><span className="eyebrow light">Jobs & opportunities</span><h1>Verified recruitment notices from official sources</h1><p>Search government and private opportunities gathered from approved official portals. Unclear details are held for review, never guessed.</p><form className="jobs-search" onSubmit={submit}><label className="visually-hidden" htmlFor="job-search">Search job notices</label><input id="job-search" type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search title, organization, qualification or location"/><button type="submit">Search jobs</button></form><div className="jobs-trust-row"><span>✓ Official links only</span><span>✓ Updated daily</span><span>✓ No OTP, PIN or password requested</span></div></section>
    <section className="jobs-directory" aria-labelledby="jobs-directory-title"><div className="section-header inline"><div><span className="eyebrow">Opportunity directory</span><h2 id="jobs-directory-title">Current published notices</h2>{!loading&&!error&&<p className="job-results-summary" role="status">{jobs.length} verified notice{jobs.length===1?'':'s'}{submitted?` matching “${submitted}”`:''}</p>}</div><div className="job-filter-tabs" role="group" aria-label="Filter jobs by type"><button type="button" className={!type?'active':''} onClick={()=>setType('')} aria-pressed={!type}>All</button><button type="button" className={type==='government'?'active':''} onClick={()=>setType('government')} aria-pressed={type==='government'}>Government</button><button type="button" className={type==='private'?'active':''} onClick={()=>setType('private')} aria-pressed={type==='private'}>Private</button></div></div>
      {loading&&<div className="dashboard-state"><div className="loading-dot"/><p>Loading current notices…</p></div>}{error&&<div className="dashboard-state error-state" role="alert"><p>{error}</p><button onClick={load}>Try again</button></div>}{!loading&&!error&&!jobs.length&&<div className="empty-dashboard"><h3>No matching published notices</h3><p>Try a broader search. Notices with incomplete or uncertain data remain in administrator review.</p></div>}<div className="jobs-list">{jobs.map(job=><JobCard key={job.id} job={job}/>)}</div>
    </section>
    <section className="job-source-transparency"><div><span className="eyebrow">Source transparency</span><h2>Approved official sources</h2><p>This independent website links to source organizations; it does not represent them. Always confirm eligibility, fees and deadlines in the official notice.</p></div><div className="source-chip-list">{sources.map(source=><a key={source.key} href={source.listing_url} target="_blank" rel="noopener noreferrer"><span className={`source-status ${source.last_sync_status==='success'?'healthy':''}`}/><strong>{source.name}</strong><small>{source.last_sync_completed_at?`Last checked ${new Date(source.last_sync_completed_at).toLocaleString('en-IN')}`:'Scheduled for daily checks'}</small></a>)}</div></section>
  </div>
}
