import React, { useEffect, useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { login, warmAuthServer } from '../services/auth'
import '../styles/auth.css'
import AuthLayout from '../components/ui/AuthLayout'

export default function Login(){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const nav=useNavigate(); const location=useLocation()
  const params=new URLSearchParams(location.search); const requestedReturn=params.get('returnTo');
  const safeReturn=requestedReturn && requestedReturn.startsWith('/') && !requestedReturn.startsWith('//') ? requestedReturn : '/my-orders'
  useEffect(()=>{void warmAuthServer()},[])
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setError('');setBusy(true);void import('./MyOrders');try{const res=await login(email,password);if(res?.token)nav(safeReturn,{replace:true});else setError(res?.error||'Login failed. Please check your details.')}catch(err:any){setError(err?.code==='ECONNABORTED'?'The secure server is still starting. Please try again once.':err?.response?.data?.error||'Unable to sign in right now. Please try again.')}finally{setBusy(false)}}
  return <AuthLayout title="Client Login"><div className="auth-card auth-card-modern" role="region" aria-labelledby="login-heading"><div className="auth-intro"><h2 id="login-heading">Welcome back</h2><p className="muted">Sign in to track public service requests and manage your account.</p>{requestedReturn&&<p className="muted">After signing in, you’ll return to the service you selected.</p>}</div><form onSubmit={submit} className="auth-form" aria-label="Client login form"><label className="form-label">Email Address<span className="required">*</span><input className="form-input" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="form-label">Password<span className="required">*</span><div className="password-field"><input className="form-input" type={showPassword?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={showPassword?'Hide password':'Show password'} className="password-toggle" onClick={()=>setShowPassword(s=>!s)}>{showPassword?'Hide':'Show'}</button></div></label>{error&&<p className="info" role="alert">{error}</p>}{busy&&<p className="auth-hint" role="status">Signing you in securely…</p>}<button type="submit" className="btn btn-primary btn-block" disabled={busy}>{busy?'Signing in…':'Client Login'}</button><div className="auth-bottom"><Link className="auth-secondary-link" to="/request-reset">Forgot password?</Link><Link to={`/register${requestedReturn?`?returnTo=${encodeURIComponent(safeReturn)}`:''}`} className="auth-link">Create account</Link></div></form></div></AuthLayout>
}
