import React,{useEffect,useMemo,useState} from 'react'
import axios from 'axios'
import {Link,useParams} from 'react-router-dom'
import {apiBase} from '../services/apiBase'
import {authHeader} from '../services/auth'
import {PROVIDER} from '../services/config'
import FeeSummary from '../components/ui/FeeSummary'
import PaymentPanel from '../components/ui/PaymentPanel'

const REQUEST_TIMEOUT_MS=15000
const MAX_FILES=20
const MAX_BYTES=10*1024*1024
const REFUND_ASSISTANCE_MESSAGE='Please contact the administrator for refund assistance. No cancellation fee is charged.'
const PROTECTED_EDIT_KEYS=new Set(['service_name','request_mode','job_id','job_slug','job_title','job_organization','job_deadline','job_official_notice_url','job_application_url','job_source','job_source_key','job_official_fee','job_official_fee_notice_text','job_official_fee_assessment'])
type RequirementField={key:string;label?:string;type?:'text'|'date'|'select';options?:string[];placeholder?:string}

export default function OrderDetail(){
 const {id}=useParams();const [payload,setPayload]=useState<any>(null);const [serviceMeta,setServiceMeta]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [uploadMsg,setUploadMsg]=useState('');const [cancelling,setCancelling]=useState(false);const [actionMessage,setActionMessage]=useState('');const [deletingDocument,setDeletingDocument]=useState<number|null>(null);const [editing,setEditing]=useState(false);const [editData,setEditData]=useState<Record<string,string>>({});const [savingEdit,setSavingEdit]=useState(false);const [selectedFiles,setSelectedFiles]=useState<File[]>([]);const [uploading,setUploading]=useState(false)
 const load=async()=>{if(!id)return;setLoading(true);setError('');try{const r=await axios.get(`${apiBase}/orders/${id}`,{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setPayload(r.data);const serviceId=r.data?.order?.service_id;if(serviceId){axios.get(`${apiBase}/services/${serviceId}`,{timeout:REQUEST_TIMEOUT_MS}).then(meta=>setServiceMeta(meta.data)).catch(()=>setServiceMeta(null))}}catch(e:any){setError(e?.code==='ECONNABORTED'?'The server took too long to respond. Please try again.':e?.response?.data?.error||'Unable to load this request.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[id])
 const download=async(attachment:any)=>{try{const response=await fetch(`${apiBase}/uploads/${attachment.id}/download`,{headers:authHeader()});if(!response.ok)throw new Error();const type=response.headers.get('content-type')||'';if(type.includes('application/json')){const body=await response.json();if(body.url){window.open(body.url,'_blank','noopener,noreferrer');return}throw new Error()}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=attachment.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setUploadMsg('Document download failed. Please try again.')}}
 const removeDocument=async(attachment:any)=>{if(deletingDocument||!window.confirm(`Permanently remove ${attachment.filename}? This cannot be undone.`))return;setDeletingDocument(attachment.id);setUploadMsg('');try{const response=await axios.delete(`${apiBase}/uploads/${attachment.id}`,{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setUploadMsg(response.data.message);await load()}catch(e:any){setUploadMsg(e?.response?.data?.error||'Unable to remove this document. Please try again.')}finally{setDeletingDocument(null)}}
 const cancelRequest=async()=>{if(!payload?.order||cancelling)return;const refundContact=`${REFUND_ASSISTANCE_MESSAGE}\n\nAdministrator: ${PROVIDER.name}\nPhone: ${PROVIDER.phone} / ${PROVIDER.phone2}\nEmail: ${PROVIDER.email}`;if(!window.confirm(`Cancel request ${payload.order.order_code}? This stops further processing and cannot be undone.\n\n${refundContact}`))return;setCancelling(true);setActionMessage('');try{const response=await axios.post(`${apiBase}/orders/${payload.order.id}/cancel`,{}, {headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setActionMessage(`${response.data.message} ${REFUND_ASSISTANCE_MESSAGE}`);await load()}catch(e:any){setActionMessage(e?.response?.data?.error||'Unable to cancel this request. Please contact the provider.')}finally{setCancelling(false)}}
 if(loading)return <div className="dashboard-state"><div className="loading-dot"/><p>Loading request...</p></div>
 if(error||!payload?.order)return <div className="dashboard-state error-state"><h2>Request unavailable</h2><p>{error||'This request could not be found.'}</p><button onClick={load}>Try again</button><Link className="btn btn-primary" to="/my-orders">Back to requests</Link></div>
 const order=payload.order;const data=order.application_data||{};const history=payload.history||[];const attachments=payload.attachments||[];const notifications=payload.notifications||[];const terminal=['Completed','Cancelled','Rejected'].includes(order.status);const canCancel=['New','Submitted','Pending','Documents Required'].includes(order.status);const canEdit=canCancel;const canUpload=['New','Submitted','Pending','Under Review','Documents Required','In Progress'].includes(order.status)
 const requirementFields:RequirementField[]=Array.isArray(serviceMeta?.requirements?.fields)?serviceMeta.requirements.fields:[]
 const editableFields=useMemo(()=>{const byKey=new Map<string,RequirementField>();requirementFields.forEach(field=>{if(field?.key&&!PROTECTED_EDIT_KEYS.has(field.key))byKey.set(field.key,field)});Object.entries(data).forEach(([key,value])=>{if(!PROTECTED_EDIT_KEYS.has(key)&&['string','number','boolean'].includes(typeof value)&&!byKey.has(key))byKey.set(key,{key,label:key.replace(/_/g,' ')})});return Array.from(byKey.values())},[serviceMeta,data])
 const beginEdit=()=>{const initial:Record<string,string>={};editableFields.forEach(field=>{initial[field.key]=data[field.key]==null?'':String(data[field.key])});setEditData(initial);setActionMessage('');setEditing(true)}
 const saveEdit=async()=>{if(!canEdit||savingEdit)return;setSavingEdit(true);setActionMessage('');try{const application_data:any={...data};editableFields.forEach(field=>{application_data[field.key]=editData[field.key]??''});const response=await axios.put(`${apiBase}/orders/${order.id}`,{application_data},{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setActionMessage(response.data.message||'Application updated.');setEditing(false);await load()}catch(e:any){setActionMessage(e?.response?.data?.error||'Unable to save application changes.')}finally{setSavingEdit(false)}}
 const chooseFiles=(files:File[])=>{setUploadMsg('');const allowed=files.filter(file=>/\.(pdf|png|jpe?g)$/i.test(file.name)&&file.size<=MAX_BYTES);if(allowed.length!==files.length)setUploadMsg('Only PDF, PNG and JPG/JPEG files up to 10 MB each can be uploaded.');setSelectedFiles(allowed.slice(0,Math.max(0,MAX_FILES-attachments.length)))}
 const uploadDocuments=async()=>{if(!selectedFiles.length||uploading||!canUpload)return;setUploading(true);setUploadMsg('');let uploaded=0;try{for(const file of selectedFiles){const form=new FormData();form.append('file',file);form.append('order_id',String(order.id));await axios.post(`${apiBase}/uploads/`,form,{headers:authHeader(),timeout:30000});uploaded++}setUploadMsg(`${uploaded} document${uploaded===1?'':'s'} uploaded successfully.`);setSelectedFiles([]);await load()}catch(e:any){setUploadMsg(e?.response?.data?.error||`Uploaded ${uploaded} document${uploaded===1?'':'s'} before an upload failed. Please try the remaining file(s).`);await load()}finally{setUploading(false)}}
 const suggestedDocuments:string[]=Array.isArray(serviceMeta?.requirements?.documents)?serviceMeta.requirements.documents:[]
 return <div className="client-dashboard">
  <section className="dashboard-hero"><div><span className="eyebrow">Application {order.order_code}</span><h1>{order.service}</h1><p>Submitted {new Date(order.created_at).toLocaleString()} · Last updated {new Date(order.updated_at||order.created_at).toLocaleString()}</p></div><span className={`status-pill status-${String(order.status||'').toLowerCase().replace(/\s+/g,'-')}`}>{order.status}</span></section>
  <FeeSummary data={order}/>
  {order.status==='Cancelled'&&<section className="dashboard-section"><h2>Refund assistance</h2><p className="info">{REFUND_ASSISTANCE_MESSAGE}</p><address className="contact-address"><strong>{PROVIDER.name}</strong><a href={`tel:${PROVIDER.phone}`}>{PROVIDER.phone}</a><a href={`tel:${PROVIDER.phone2}`}>{PROVIDER.phone2}</a><a href={`mailto:${PROVIDER.email}`}>{PROVIDER.email}</a></address></section>}
  {!terminal&&<PaymentPanel order={order}/>} 
  <section className="dashboard-section"><h2>Application progress</h2><div className="request-timeline">{history.length?history.map((item:any)=><div className="timeline-item active" key={item.id}><strong>{item.new_status}</strong><span>{new Date(item.created_at).toLocaleString()}</span>{item.note&&<small>{item.note}</small>}</div>):<div className="timeline-item active"><strong>Application submitted</strong><span>{new Date(order.created_at).toLocaleString()}</span></div>}</div></section>
  <section className="dashboard-section"><div className="section-heading-row"><div><h2>Application information</h2><p>These are the details currently shared with the admin. You can fill in details you skipped earlier while this request is still editable.</p></div>{canEdit&&!editing&&<button className="btn-secondary" type="button" onClick={beginEdit}>Edit / Complete Application Details</button>}</div>{editing?<><div className="request-form">{editableFields.length?editableFields.map(field=><label key={field.key}>{field.label||field.key.replace(/_/g,' ')}{field.type==='select'&&field.options?.length?<select value={editData[field.key]??''} onChange={event=>setEditData(current=>({...current,[field.key]:event.target.value}))}><option value="">Select</option>{field.options.map(option=><option key={option} value={option}>{option}</option>)}</select>:<input type={field.type==='date'?'date':'text'} placeholder={field.placeholder||''} value={editData[field.key]??''} onChange={event=>setEditData(current=>({...current,[field.key]:event.target.value}))}/>}</label>):<p>No editable application fields are available for this request.</p>}</div><p className="info">Blank fields are allowed. Saving updates the same application and automatically notifies the admin.</p><div className="cta-row"><button type="button" className="btn-secondary" disabled={savingEdit} onClick={()=>setEditing(false)}>Cancel edit</button><button type="button" disabled={savingEdit} onClick={saveEdit}>{savingEdit?'Saving…':'Save Changes'}</button></div></>:<div className="request-summary">{Object.entries(data).filter(([key])=>key!=='service_name').map(([key,value])=><p key={key}><strong>{key.replace(/_/g,' ')}:</strong> {String(value||'—')}</p>)}</div>}</section>
  <section className="dashboard-section"><h2>Documents</h2>{suggestedDocuments.length>0&&<div className="request-summary"><strong>Useful documents for this service</strong>{suggestedDocuments.map(item=><p key={item}>• {item}</p>)}</div>}{attachments.length?<ul className="document-list">{attachments.map((attachment:any)=><li key={attachment.id}><span>{attachment.filename}<small>{attachment.uploaded_by_role==='admin'?'Delivered by admin':'Uploaded with your request'}</small></span><div className="document-actions"><button className="btn-secondary" type="button" onClick={()=>download(attachment)}>View / download</button>{canUpload&&attachment.uploaded_by_role==='client'&&<button className="danger-button" type="button" disabled={deletingDocument===attachment.id} onClick={()=>removeDocument(attachment)}>{deletingDocument===attachment.id?'Removing…':'Remove'}</button>}</div></li>)}</ul>:<p>No documents attached yet.</p>}{canUpload&&attachments.length<MAX_FILES&&<div className="request-form"><label>Add documents<input type="file" multiple accept=".pdf,.png,.jpg,.jpeg,application/pdf,image/png,image/jpeg" onChange={event=>chooseFiles(Array.from(event.target.files||[]))}/></label>{selectedFiles.length>0&&<><p>{selectedFiles.length} file{selectedFiles.length===1?'':'s'} ready to upload.</p><button type="button" disabled={uploading} onClick={uploadDocuments}>{uploading?'Uploading…':'Upload Documents'}</button></>}<small>You can add documents later without creating a new application. Maximum 20 files per request, 10 MB each. Never upload passwords, OTPs, PINs or CVV details.</small></div>}{uploadMsg&&<p className="info" role="status">{uploadMsg}</p>}</section>
  {notifications.length>0&&<section className="dashboard-section"><h2>Application notifications</h2><div className="notification-list">{notifications.map((item:any)=><article key={item.id} className={item.is_read?'notification-card':'notification-card unread'}><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.created_at).toLocaleString()}</small>{!item.is_read&&<button className="btn-secondary" type="button" onClick={async()=>{await axios.post(`${apiBase}/notifications/${item.id}/read`,{}, {headers:authHeader()});setPayload({...payload,notifications:notifications.map((notification:any)=>notification.id===item.id?{...notification,is_read:true}:notification)})}}>Mark read</button>}</article>)}</div></section>}
  {payload.grievances?.length>0&&<section className="dashboard-section"><h2>Help / grievances</h2>{payload.grievances.map((item:any)=><div className="request-summary" key={item.id}><p>{item.message||item.description||'Grievance submitted.'}</p><small>{item.status||'Submitted'}</small></div>)}</section>}
  <section className="dashboard-section"><h2>Application actions</h2><p>{terminal?'This application is closed.':order.status==='Documents Required'?'Add the requested document here or chat with Admin if you need clarification.':'Your application is being processed. Updates appear here.'}</p>{actionMessage&&<p className="info" role="status">{actionMessage}</p>}<div className="cta-row">{canEdit&&!editing&&<button type="button" className="btn-secondary" onClick={beginEdit}>Edit / Complete Application Details</button>}{canCancel&&<button type="button" className="btn-secondary" disabled={cancelling} onClick={cancelRequest}>{cancelling?'Cancelling…':'Cancel request'}</button>}{order.status==='Documents Required'&&<Link className="btn btn-primary" to="/messages">Chat with Admin</Link>}{!terminal&&<Link className="btn btn-secondary" to={`/submit-grievance?order_id=${order.id}`}>Get help</Link>}<Link className="btn btn-secondary" to="/my-orders#applications">Back to applications</Link></div></section>
 </div>
}
