import React,{useEffect,useState} from 'react'
import axios from 'axios'
import {Link,useParams} from 'react-router-dom'
import {apiBase} from '../services/apiBase'
import {authHeader} from '../services/auth'

export default function OrderDetail(){
 const {id}=useParams();const [payload,setPayload]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [file,setFile]=useState<File|null>(null);const [uploadMsg,setUploadMsg]=useState('');const [uploading,setUploading]=useState(false)
 const load=()=>{if(!id)return;setLoading(true);axios.get(`${apiBase}/orders/${id}`,{headers:authHeader()}).then(r=>setPayload(r.data)).catch(e=>setError(e?.response?.data?.error||'Unable to load this request.')).finally(()=>setLoading(false))}
 useEffect(load,[id])
 const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!file||!payload?.order)return;setUploading(true);setUploadMsg('Uploading…');try{const fd=new FormData();fd.append('file',file);fd.append('order_id',String(payload.order.id));const r=await axios.post(`${apiBase}/uploads`,fd,{headers:authHeader()});setUploadMsg(r.data.message);setFile(null);load()}catch(e:any){setUploadMsg(e?.response?.data?.error||'Upload failed. Please try again.')}finally{setUploading(false)}}
 if(loading)return <div className="dashboard-state"><div className="loading-dot"/><p>Loading request...</p></div>
 if(error||!payload?.order)return <div className="dashboard-state error-state"><h2>Request unavailable</h2><p>{error||'This request could not be found.'}</p><Link className="btn btn-primary" to="/my-orders">Back to requests</Link></div>
 const order=payload.order;const data=order.application_data||{};const history=payload.history||[];const attachments=payload.attachments||[];const terminal=['Completed','Cancelled','Rejected'].includes(order.status);const canUpload=!terminal
 return <div className="client-dashboard"><section className="dashboard-hero"><div><span className="eyebrow">Request {order.order_code}</span><h1>{order.service}</h1><p>Submitted {new Date(order.created_at).toLocaleString()}</p></div><span className={`status-pill status-${String(order.status||'').toLowerCase().replace(/\s+/g,'-')}`}>{order.status}</span></section>
  <section className="dashboard-section"><h2>Request progress</h2><div className="request-timeline">{history.length?history.map((h:any)=><div className="timeline-item active" key={h.id}><strong>{h.new_status}</strong><span>{new Date(h.created_at).toLocaleString()}</span>{h.note&&<small>{h.note}</small>}</div>):<div className="timeline-item active"><strong>Request submitted</strong><span>{new Date(order.created_at).toLocaleString()}</span></div>}</div></section>
  <section className="dashboard-section"><h2>Application information</h2><div className="request-summary">{Object.entries(data).filter(([k])=>k!=='service_name').map(([k,v])=><p key={k}><strong>{k.replace(/_/g,' ')}:</strong> {String(v||'—')}</p>)}</div></section>
  <section className="dashboard-section"><h2>Documents</h2>{attachments.length?<ul className="document-list">{attachments.map((a:any)=><li key={a.id}><span>{a.filename}</span><a href={`${apiBase}/uploads/${a.id}/download`} target="_blank" rel="noreferrer">View / download</a></li>)}</ul>:<p>No documents uploaded yet.</p>}{canUpload&&<><p>{order.status==='Documents Required'?'The provider requested additional documents. Upload them here to continue processing.':'You can upload supporting documents for this request here.'}</p><form onSubmit={upload} className="upload-card"><input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>{const selected=e.target.files?.[0]||null;if(selected&&selected.size>10*1024*1024){setUploadMsg('Please choose a file smaller than 10 MB.');return}setFile(selected)}}/><button type="submit" disabled={!file||uploading}>{uploading?'Uploading…':'Upload document'}</button>{uploadMsg&&<p className="info" role="status">{uploadMsg}</p>}</form></>}</section>
  {payload.grievances?.length>0&&<section className="dashboard-section"><h2>Help / grievances</h2>{payload.grievances.map((g:any)=><div className="request-summary" key={g.id}><p>{g.message||g.description||'Grievance submitted.'}</p><small>{g.status||'Submitted'}</small></div>)}</section>}
  <section className="dashboard-section"><h2>Request actions</h2><p>{terminal?'This request is closed.':order.status==='Documents Required'?'Please provide the requested documents above. The provider will review them and continue processing.':'Your request is being handled through the provider workflow. Any required action will appear here.'}</p><div className="cta-row">{!terminal&&<Link className="btn btn-secondary" to={`/submit-grievance?order_id=${order.id}`}>Get help</Link>}{order.status==='Completed'&&<Link className="btn btn-primary" to={`/submit-review?order_id=${order.id}`}>Leave a review</Link>}<Link className="btn btn-secondary" to="/my-orders">Back to requests</Link></div></section>
 </div>
}
