import React,{useEffect,useMemo,useState} from 'react'
import axios from 'axios'
import {Link,useParams} from 'react-router-dom'
import {apiBase} from '../services/apiBase'
import {authHeader} from '../services/auth'
import FeeSummary from '../components/ui/FeeSummary'
import PaymentPanel from '../components/ui/PaymentPanel'

const REQUEST_TIMEOUT_MS=15000
const PROTECTED_EDIT_KEYS=new Set(['service_name','request_mode','job_id','job_slug','job_title','job_organization','job_deadline','job_official_notice_url','job_application_url','job_source','job_source_key','job_official_fee','job_official_fee_notice_text','job_official_fee_assessment'])
export default function OrderDetail(){
 const {id}=useParams();const [payload,setPayload]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [uploadMsg,setUploadMsg]=useState('');const [cancelling,setCancelling]=useState(false);const [actionMessage,setActionMessage]=useState('');const [deletingDocument,setDeletingDocument]=useState<number|null>(null);const [editing,setEditing]=useState(false);const [editData,setEditData]=useState<Record<string,string>>({});const [savingEdit,setSavingEdit]=useState(false)
 const load=async()=>{if(!id)return;setLoading(true);setError('');try{const r=await axios.get(`${apiBase}/orders/${id}`,{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setPayload(r.data)}catch(e:any){setError(e?.code==='ECONNABORTED'?'The server took too long to respond. Please try again.':e?.response?.data?.error||'Unable to load this request.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[id])
 const download=async(attachment:any)=>{try{const response=await fetch(`${apiBase}/uploads/${attachment.id}/download`,{headers:authHeader()});if(!response.ok)throw new Error();const type=response.headers.get('content-type')||'';if(type.includes('application/json')){const body=await response.json();if(body.url){window.open(body.url,'_blank','noopener,noreferrer');return}throw new Error()}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=attachment.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setUploadMsg('Document download failed. Please try again.')}}
 const removeDocument=async(attachment:any)=>{if(deletingDocument||!window.confirm(`Permanently remove ${attachment.filename}? This cannot be undone.`))return;setDeletingDocument(attachment.id);setUploadMsg('');try{const response=await axios.delete(`${apiBase}/uploads/${attachment.id}`,{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setUploadMsg(response.data.message);await load()}catch(e:any){setUploadMsg(e?.response?.data?.error||'Unable to remove this document. Please try again.')}finally{setDeletingDocument(null)}}
 const cancelRequest=async()=>{if(!payload?.order||cancelling)return;if(!window.confirm(`Cancel request ${payload.order.order_code}? This stops further processing and cannot be undone.`))return;setCancelling(true);setActionMessage('');try{const response=await axios.post(`${apiBase}/orders/${payload.order.id}/cancel`,{}, {headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setActionMessage(response.data.message);await load()}catch(e:any){setActionMessage(e?.response?.data?.error||'Unable to cancel this request. Please contact the provider.')}finally{setCancelling(false)}}
 if(loading)return <div className="dashboard-state"><div className="loading-dot"/><p>Loading request...</p></div>
 if(error||!payload?.order)return <div className="dashboard-state error-state"><h2>Request unavailable</h2><p>{error||'This request could not be found.'}</p><button onClick={load}>Try again</button><Link className="btn btn-primary" to="/my-orders">Back to requests</Link></div>
 const order=payload.order;const data=order.application_data||{};const history=payload.history||[];const attachments=payload.attachments||[];const notifications=payload.notifications||[];const terminal=['Completed','Cancelled','Rejected'].includes(order.status);const canCancel=['New','Submitted','Pending','Documents Required'].includes(order.status);const canEdit=canCancel
 const editableEntries=useMemo(()=>Object.entries(data).filter(([key,value])=>!PROTECTED_EDIT_KEYS.has(key)&&['string','number','boolean'].includes(typeof value)),[data])
 const beginEdit=()=>{const initial:Record<string,string>={};editableEntries.forEach(([key,value])=>{initial[key]=value==null?'':String(value)});setEditData(initial);setActionMessage('');setEditing(true)}
 const saveEdit=async()=>{if(!canEdit||savingEdit)return;setSavingEdit(true);setActionMessage('');try{const application_data:any={...data};for(const [key] of editableEntries)application_data[key]=editData[key]??'';const response=await axios.put(`${apiBase}/orders/${order.id}`,{application_data},{headers:authHeader(),timeout:REQUEST_TIMEOUT_MS});setActionMessage(response.data.message||'Application updated.');setEditing(false);await load()}catch(e:any){setActionMessage(e?.response?.data?.error||'Unable to save application changes.')}finally{setSavingEdit(false)}}
 return <div className="client-dashboard">
  <section className="dashboard-hero"><div><span className="eyebrow">Application {order.order_code}</span><h1>{order.service}</h1><p>Submitted {new Date(order.created_at).toLocaleString()} · Last updated {new Date(order.updated_at||order.created_at).toLocaleString()}</p></div><span className={`status-pill status-${String(order.status||'').toLowerCase().replace(/\s+/g,'-')}`}>{order.status}</span></section>
  <FeeSummary data={order}/>
  {!terminal&&<PaymentPanel order={order}/>} 
  <section className="dashboard-section"><h2>Application progress</h2><div className="request-timeline">{history.length?history.map((item:any)=><div className="timeline-item active" key={item.id}><strong>{item.new_status}</strong><span>{new Date(item.created_at).toLocaleString()}</span>{item.note&&<small>{item.note}</small>}</div>):<div className="timeline-item active"><strong>Application submitted</strong><span>{new Date(order.created_at).toLocaleString()}</span></div>}</div></section>
  <section className="dashboard-section"><div className="section-heading-row"><div><h2>Application information</h2><p>These are the details currently shared with the admin for this request.</p></div>{canEdit&&!editing&&<button className="btn-secondary" type="button" onClick={beginEdit}>Edit Application Details</button>}</div>{editing?<><div className="request-form">{editableEntries.length?editableEntries.map(([key])=><label key={key}>{key.replace(/_/g,' ')}<input value={editData[key]??''} onChange={event=>setEditData(current=>({...current,[key]:event.target.value}))}/></label>):<p>No editable application details are available for this request.</p>}</div><p className="info">Saving an edit updates the same application and automatically notifies the admin that the client changed it.</p><div className="cta-row"><button type="button" className="btn-secondary" disabled={savingEdit} onClick={()=>setEditing(false)}>Cancel edit</button><button type="button" disabled={savingEdit} onClick={saveEdit}>{savingEdit?'Saving…':'Save Changes'}</button></div></>:<div className="request-summary">{Object.entries(data).filter(([key])=>key!=='service_name').map(([key,value])=><p key={key}><strong>{key.replace(/_/g,' ')}:</strong> {String(value||'—')}</p>)}</div>}</section>
  <section className="dashboard-section"><h2>Documents</h2>{attachments.length?<ul className="document-list">{attachments.map((attachment:any)=><li key={attachment.id}><span>{attachment.filename}<small>{attachment.uploaded_by_role==='admin'?'Delivered by admin':'Uploaded with your request'}</small></span><div className="document-actions"><button className="btn-secondary" type="button" onClick={()=>download(attachment)}>View / download</button>{!terminal&&attachment.uploaded_by_role==='client'&&<button className="danger-button" type="button" disabled={deletingDocument===attachment.id} onClick={()=>removeDocument(attachment)}>{deletingDocument===attachment.id?'Removing…':'Remove'}</button>}</div></li>)}</ul>:<p>No documents attached.</p>}{uploadMsg&&<p className="info" role="status">{uploadMsg}</p>}</section>
  {notifications.length>0&&<section className="dashboard-section"><h2>Application notifications</h2><div className="notification-list">{notifications.map((item:any)=><article key={item.id} className={item.is_read?'notification-card':'notification-card unread'}><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.created_at).toLocaleString()}</small>{!item.is_read&&<button className="btn-secondary" type="button" onClick={async()=>{await axios.post(`${apiBase}/notifications/${item.id}/read`,{}, {headers:authHeader()});setPayload({...payload,notifications:notifications.map((notification:any)=>notification.id===item.id?{...notification,is_read:true}:notification)})}}>Mark read</button>}</article>)}</div></section>}
  {payload.grievances?.length>0&&<section className="dashboard-section"><h2>Help / grievances</h2>{payload.grievances.map((item:any)=><div className="request-summary" key={item.id}><p>{item.message||item.description||'Grievance submitted.'}</p><small>{item.status||'Submitted'}</small></div>)}</section>}
  <section className="dashboard-section"><h2>Application actions</h2><p>{terminal?'This application is closed.':order.status==='Documents Required'?'Chat with Admin about the requested document.':'Your application is being processed. Updates appear here.'}</p>{actionMessage&&<p className="info" role="status">{actionMessage}</p>}<div className="cta-row">{canEdit&&!editing&&<button type="button" className="btn-secondary" onClick={beginEdit}>Edit Application Details</button>}{canCancel&&<button type="button" className="btn-secondary" disabled={cancelling} onClick={cancelRequest}>{cancelling?'Cancelling…':'Cancel request'}</button>}{order.status==='Documents Required'&&<Link className="btn btn-primary" to="/messages">Chat with Admin</Link>}{!terminal&&<Link className="btn btn-secondary" to={`/submit-grievance?order_id=${order.id}`}>Get help</Link>}<Link className="btn btn-secondary" to="/my-orders#applications">Back to applications</Link></div></section>
 </div>
}
