import React,{useEffect,useMemo,useState} from 'react'
import {Link,useLocation,useNavigate,useParams} from 'react-router-dom'
import axios from 'axios'
import {apiBase} from '../services/apiBase'
import {fetchServiceCatalog,readCachedServices,slugifyServiceName} from '../services/serviceCatalog'
import {getSession} from '../services/session'
import {getToken} from '../services/localStorage'
import FeeSummary from '../components/ui/FeeSummary'
import Seo from '../components/ui/Seo'
import '../styles/workspace-modern.css'

type Field={key:string;label:string;placeholder:string;required?:boolean}

type Flow={kind:string;title:string;fields:Field[]}

function flowFor(service:any):Flow{
 const text=`${service?.name||''} ${service?.category||''} ${service?.keywords||''}`.toLowerCase()
 if(text.includes('mobile')&&text.includes('recharge'))return{kind:'mobile_recharge',title:'Mobile recharge details',fields:[{key:'mobile_number',label:'Mobile number',placeholder:'10-digit mobile number',required:true},{key:'operator',label:'Operator',placeholder:'Jio, Airtel, Vi, BSNL, etc.',required:true},{key:'circle',label:'Circle / state',placeholder:'Telangana, Andhra Pradesh, etc.'},{key:'requested_amount_inr',label:'Recharge amount (₹)',placeholder:'Enter recharge amount',required:true}]}
 if(text.includes('postpaid'))return{kind:'mobile_postpaid',title:'Postpaid bill details',fields:[{key:'mobile_number',label:'Postpaid mobile number',placeholder:'Mobile number',required:true},{key:'operator',label:'Operator',placeholder:'Operator name',required:true},{key:'requested_amount_inr',label:'Bill amount (₹)',placeholder:'Amount shown on the bill',required:true}]}
 if(text.includes('dth'))return{kind:'dth_recharge',title:'DTH recharge details',fields:[{key:'subscriber_id',label:'Subscriber / customer ID',placeholder:'DTH subscriber ID',required:true},{key:'provider',label:'DTH provider',placeholder:'Tata Play, Airtel Digital TV, Dish TV, etc.',required:true},{key:'requested_amount_inr',label:'Recharge amount (₹)',placeholder:'Enter recharge amount',required:true}]}
 if(text.includes('fastag'))return{kind:'fastag_recharge',title:'FASTag recharge details',fields:[{key:'vehicle_number',label:'Vehicle number',placeholder:'Vehicle registration number',required:true},{key:'registered_mobile',label:'Registered mobile number',placeholder:'Mobile linked to FASTag'},{key:'provider',label:'Issuer / bank',placeholder:'FASTag issuer or bank'},{key:'requested_amount_inr',label:'Recharge amount (₹)',placeholder:'Enter recharge amount',required:true}]}
 if(text.includes('broadband')||text.includes('landline'))return{kind:'broadband_bill',title:'Broadband / landline bill details',fields:[{key:'account_id',label:'Customer / account ID',placeholder:'Account or landline number',required:true},{key:'provider',label:'Provider',placeholder:'Provider name',required:true},{key:'requested_amount_inr',label:'Bill amount (₹)',placeholder:'Amount shown on the bill',required:true}]}
 if(text.includes('gas'))return{kind:'gas_bill',title:'Gas bill details',fields:[{key:'consumer_number',label:'Consumer number',placeholder:'Consumer / BP number',required:true},{key:'provider',label:'Gas provider',placeholder:'Provider name',required:true},{key:'requested_amount_inr',label:'Bill amount (₹)',placeholder:'Amount shown on the bill',required:true}]}
 if(text.includes('electric'))return{kind:'electricity_bill',title:'Electricity bill details',fields:[{key:'consumer_number',label:'Consumer / service number',placeholder:'Consumer or service number',required:true},{key:'provider',label:'Electricity provider',placeholder:'DISCOM / provider name',required:true},{key:'requested_amount_inr',label:'Bill amount (₹)',placeholder:'Amount shown on the bill',required:true}]}
 if(text.includes('water'))return{kind:'water_bill',title:'Water bill details',fields:[{key:'consumer_number',label:'Consumer / connection number',placeholder:'Connection or consumer number',required:true},{key:'provider',label:'Water provider',placeholder:'Board / municipality name',required:true},{key:'requested_amount_inr',label:'Bill amount (₹)',placeholder:'Amount shown on the bill',required:true}]}
 return{kind:'bill_payment',title:'Bill payment details',fields:[{key:'consumer_number',label:'Consumer / account number',placeholder:'Consumer, account or reference number',required:true},{key:'provider',label:'Provider',placeholder:'Provider name',required:true},{key:'requested_amount_inr',label:'Amount (₹)',placeholder:'Amount to be paid',required:true}]}
}

export default function RechargeBillRequest(){
 const {slug}=useParams();const location=useLocation();const navigate=useNavigate();const session=getSession()
 const [catalog,setCatalog]=useState<any[]>(()=>readCachedServices(true));const [loading,setLoading]=useState(catalog.length===0);const [step,setStep]=useState<1|2|3>(1);const [answers,setAnswers]=useState<Record<string,string>>({});const [notes,setNotes]=useState('');const [accepted,setAccepted]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [order,setOrder]=useState<any>(null)
 useEffect(()=>{let active=true;fetchServiceCatalog().then(items=>{if(active)setCatalog(items)}).catch(()=>{if(active)setError('Unable to load recharge and bill services right now.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 const service=useMemo(()=>catalog.find((item:any)=>(item.slug||slugifyServiceName(item.name))===slug),[catalog,slug])
 const flow=useMemo(()=>flowFor(service),[service])
 const missing=flow.fields.filter(field=>field.required&&!String(answers[field.key]||'').trim())
 const amount=Number(answers.requested_amount_inr||0)
 const returnTo=encodeURIComponent(location.pathname)
 const review=()=>{setError('');if(missing.length){setError(`Please complete: ${missing.map(item=>item.label).join(', ')}.`);return}if(!Number.isFinite(amount)||amount<=0){setError('Enter a valid recharge or bill amount.');return}setStep(2);window.scrollTo({top:0,behavior:'smooth'})}
 const submit=async()=>{if(!accepted||!service)return;setBusy(true);setError('');try{const application_data={payment_request_type:flow.kind,payment_request_label:flow.title,requested_payment_amount_inr:amount,...answers,notes:notes.trim(),service_name:service.name,request_mode:'guided'};const response=await axios.post(`${apiBase}/orders/`,{service_id:Number(service.id),application_data},{headers:{Authorization:`Bearer ${getToken()}`},timeout:15000});setOrder(response.data.order);setStep(3);window.scrollTo({top:0,behavior:'smooth'})}catch(err:any){setError(err?.response?.data?.error||'Unable to submit this request. Please try again.')}finally{setBusy(false)}}
 if(loading)return <div className="dashboard-state" role="status"><div className="loading-dot"/><p>Loading payment service…</p></div>
 if(!service)return <div className="empty-state"><h2>Payment service unavailable</h2><p>{error||'Choose another recharge or bill service.'}</p><Link className="btn btn-primary" to="/recharge-bills">Back to Recharge & Bills</Link></div>
 if(!session)return <><Seo title={service.name} description={`Guided request for ${service.name}.`} path={location.pathname} index={false}/><div className="payment-flow-page"><section className="payment-flow-hero"><span className="eyebrow">Recharge & Bill Payments</span><h1>{service.name}</h1><p>Sign in to enter the payment details, review the amount and submit a trackable request.</p><FeeSummary data={service}/><div className="button-row"><Link className="btn btn-primary" to={`/login?returnTo=${returnTo}`}>Sign in & continue</Link><Link className="btn btn-secondary" to={`/register?returnTo=${returnTo}`}>Create account</Link></div></section></div></>
 if(session.is_admin)return <div className="empty-state"><h2>Client payment request</h2><p>Recharge and bill requests are submitted from client accounts and managed from Applications.</p><Link className="btn btn-primary" to="/admin/orders">Open Applications</Link></div>
 return <><Seo title={service.name} description={`Guided request for ${service.name}.`} path={location.pathname} index={false}/><div className="payment-flow-page">
  <section className="payment-flow-hero"><div><span className="eyebrow">Recharge & Bill Payments</span><h1>{service.name}</h1><p>Enter only the account details needed for this request. You will be able to track it from your dashboard after submission.</p></div><Link to="/recharge-bills">← Choose another service</Link></section>
  <ol className="payment-steps" aria-label="Payment request progress"><li className={step>=1?'active':''}><b>1</b><span>Details</span></li><li className={step>=2?'active':''}><b>2</b><span>Review</span></li><li className={step>=3?'active':''}><b>3</b><span>Track</span></li></ol>
  {error&&<p className="info" role="alert">{typeof error==='string'?error:'Unable to continue.'}</p>}
  {step===1&&<section className="payment-flow-card"><header><span className="eyebrow">Step 1 of 3</span><h2>{flow.title}</h2><p>Fill in the details exactly as they appear with the operator or biller.</p></header><div className="payment-field-grid">{flow.fields.map(field=><label key={field.key}>{field.label}{field.required&&<strong> *</strong>}<input inputMode={field.key.includes('amount')||field.key.includes('mobile')?'numeric':'text'} value={answers[field.key]||''} onChange={event=>setAnswers(current=>({...current,[field.key]:event.target.value}))} placeholder={field.placeholder}/></label>)}</div><label className="payment-notes">Notes for the administrator<textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Optional: plan name, bill month, special instruction, etc."/></label><div className="payment-safety"><strong>Never enter OTP, UPI PIN, card PIN, CVV, banking password or account recovery code.</strong> The administrator may contact you only if the submitted details need clarification.</div><button className="btn btn-primary" type="button" onClick={review}>Review request →</button></section>}
  {step===2&&<section className="payment-flow-card"><header><span className="eyebrow">Step 2 of 3</span><h2>Review before submitting</h2><p>Check the number/account and amount carefully. A wrong account number can send a recharge or payment to the wrong account.</p></header><div className="payment-review-grid"><div><span>Service</span><strong>{service.name}</strong></div>{flow.fields.map(field=><div key={field.key}><span>{field.label}</span><strong>{field.key==='requested_amount_inr'?`₹${Number(answers[field.key]||0).toFixed(2)}`:(answers[field.key]||'—')}</strong></div>)}</div><FeeSummary data={service}/><p className="payment-flow-note"><strong>What happens next:</strong> your request is created first. The administrator verifies the submitted service/account details and the amount. Any payable amount or next action is shown in the application flow before processing.</p><label className="payment-consent"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)}/><span>I checked the account details and amount, and I understand I must never share OTPs, passwords or PINs.</span></label><div className="button-row"><button className="btn btn-secondary" type="button" onClick={()=>setStep(1)}>← Edit details</button><button className="btn btn-primary" type="button" disabled={!accepted||busy} onClick={submit}>{busy?'Submitting…':'Submit request'}</button></div></section>}
  {step===3&&order&&<section className="payment-flow-card payment-success"><span className="eyebrow">Step 3 of 3</span><h2>Request submitted</h2><p>Your reference number is <strong>{order.order_code}</strong>. Track verification, payment instructions and completion from My Applications.</p><div className="button-row"><Link className="btn btn-primary" to={`/my-orders/${order.id}`}>Open this request</Link><Link className="btn btn-secondary" to="/my-orders">Go to dashboard</Link></div></section>}
 </div></>
}
