import React,{useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import axios from 'axios'
import {apiBase} from '../services/apiBase'

export default function ServiceDetail(){
 const {id}=useParams();const [service,setService]=useState<any>(null);const [loading,setLoading]=useState(true);const [form,setForm]=useState({client_name:'',phone:'',email:'',description:''});const [message,setMessage]=useState('');const [error,setError]=useState('');const [lastOrder,setLastOrder]=useState<any>(null);const [file,setFile]=useState<File|null>(null);const [uploadMsg,setUploadMsg]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{if(!id)return;axios.get(`${apiBase}/services/${id}`).then(r=>setService(r.data)).catch(()=>setError('Unable to load this service right now.')).finally(()=>setLoading(false))},[id])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setMessage('');setBusy(true);try{const r=await axios.post(`${apiBase}/orders`,{...form,service_id:Number(id)});setMessage(`${r.data.message} Order: ${r.data.order.order_code}`);setLastOrder(r.data.order);setForm({client_name:'',phone:'',email:'',description:''})}catch(err:any){setError(err?.response?.data?.error||'Unable to submit your request. Please try again.')}finally{setBusy(false)}}
 const uploadFile=async(e:React.FormEvent)=>{e.preventDefault();if(!file||!lastOrder)return setUploadMsg('Choose a PDF or image first.');const fd=new FormData();fd.append('file',file);fd.append('order_id',String(lastOrder.id));try{const r=await axios.post(`${apiBase}/uploads`,fd,{headers:{'Content-Type':'multipart/form-data'}});setUploadMsg(r.data.message);setFile(null)}catch(err:any){setUploadMsg(err?.response?.data?.error||'Upload failed. Please try again.')}}
 if(loading)return <div className="empty-state">Loading service details…</div>;if(!service)return <div className="empty-state"><h2>Service unavailable</h2><p>{error||'We could not find this service.'}</p><Link className="btn btn-primary" to="/">Return home</Link></div>
 return <div className="service-detail-page"><div className="service-detail-hero"><span className="eyebrow">{service.category||'Public service'}</span><h1>{service.name}</h1><p>{service.description}</p><div className="service-detail-meta"><span>Service fee <strong>₹{service.price_inr}</strong></span><span>Independent assistance</span></div></div><div className="service-request-grid"><section className="dashboard-section"><span className="eyebrow">Request assistance</span><h2>Tell us what you need</h2><div className="trust-note"><strong>Privacy first.</strong> We will never ask for OTPs, passwords, PINs or bank details.</div><form onSubmit={submit} className="request-form"><label>Full name<input required value={form.client_name} onChange={e=>setForm({...form,client_name:e.target.value})}/></label><label>Phone<input type="tel" required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email (optional)<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Short description / notes<textarea required minLength={5} rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{error&&<p className="info" role="alert">{error}</p>}{message&&<p className="success-message" role="status">{message}</p>}<button type="submit" disabled={busy}>{busy?'Submitting…':'Submit request'}</button></form>{lastOrder&&<div className="upload-card"><span className="eyebrow">Documents</span><h3>Attach a document</h3><p>Optional: upload a PDF, JPG or PNG related to this request.</p><form onSubmit={uploadFile}><input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><button type="submit">Upload document</button></form>{uploadMsg&&<p className="info" role="status">{uploadMsg}</p>}</div>}</section><aside className="dashboard-section service-side-card"><span className="eyebrow">Need help?</span><h2>Not sure what to choose?</h2><p>Contact the service provider or submit a grievance if you need help with an existing request.</p><Link className="btn btn-secondary" to="/contact">Contact us</Link><Link className="text-link" to="/my-orders">View my requests →</Link></aside></div></div>
}
