import React,{useEffect,useState} from 'react'
import axios from 'axios'
import {apiBase} from '../services/apiBase'
import {authHeader} from '../services/auth'
import {Link,useSearchParams} from 'react-router-dom'

export default function SubmitReview(){
 const [params]=useSearchParams();const requestedOrder=params.get('order_id')||'';const [form,setForm]=useState({order_id:requestedOrder,rating:5,comment:''});const [orders,setOrders]=useState<any[]>([]);const [loadingOrders,setLoadingOrders]=useState(true);const [msg,setMsg]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{axios.get(`${apiBase}/orders/mine`,{headers:authHeader(),timeout:15000}).then(response=>{const completed=(Array.isArray(response.data)?response.data:[]).filter((item:any)=>item.status==='Completed');setOrders(completed);if(requestedOrder&&!completed.some((item:any)=>String(item.id)===requestedOrder)){setForm(current=>({...current,order_id:''}));setError('Only a completed request from your account can be reviewed.')}}).catch(()=>setError('Your completed requests could not be loaded. Please try again.')).finally(()=>setLoadingOrders(false))},[requestedOrder])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setMsg('');setError('');setBusy(true);try{const payload:any={rating:Number(form.rating),comment:form.comment};if(form.order_id)payload.order_id=Number(form.order_id);const r=await axios.post(`${apiBase}/reviews/`,payload,{headers:authHeader()});setMsg(r.data.message);setForm({order_id:'',rating:5,comment:''})}catch(err:any){setError(err?.response?.data?.error||'We could not submit your review. Please try again.')}finally{setBusy(false)}}
 return <div className="form-page"><div className="form-hero"><span className="eyebrow">Your feedback</span><h1>Review a completed service</h1><p>Your feedback helps us improve the experience.</p></div><div className="form-card">{!loadingOrders&&orders.length===0?<div className="empty-state"><h2>No completed requests to review</h2><p>A review becomes available after the provider completes one of your requests.</p><Link className="btn btn-primary" to="/my-orders#applications">View my applications</Link></div>:<form onSubmit={submit} className="request-form"><label>Completed request<select value={form.order_id} onChange={e=>setForm({...form,order_id:e.target.value})} required disabled={loadingOrders}><option value="">Select a completed request</option>{orders.map(order=><option value={order.id} key={order.id}>{order.order_code} — {order.service}</option>)}</select></label>{loadingOrders&&<p className="auth-hint" role="status">Loading completed requests…</p>}<label>Rating (1–5)<input type="number" min={1} max={5} value={form.rating} onChange={e=>setForm({...form,rating:Number(e.target.value)})}/></label><label>Comment<textarea required minLength={5} maxLength={2000} rows={6} value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})}/></label>{error&&<p className="info" role="alert">{String(error)}</p>}{msg&&<p className="success-message" role="status">{msg}</p>}<button type="submit" disabled={busy||loadingOrders||!form.order_id}>{busy?'Submitting…':'Submit review'}</button></form>}</div><p className="form-back"><Link to="/my-orders">← Back to my requests</Link></p></div>
}
