import React,{useEffect,useState} from 'react'
import axios from 'axios'
import {apiBase} from '../services/apiBase'
import {authHeader} from '../services/auth'
import {Link,useSearchParams} from 'react-router-dom'

export default function SubmitGrievance(){
 const [params]=useSearchParams();const requestedOrder=params.get('order_id')||'';const [form,setForm]=useState({order_id:requestedOrder,description:''});const [orders,setOrders]=useState<any[]>([]);const [loadingOrders,setLoadingOrders]=useState(true);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{axios.get(`${apiBase}/orders/mine`,{headers:authHeader(),timeout:15000}).then(response=>{const items=Array.isArray(response.data)?response.data:[];setOrders(items);if(requestedOrder&&!items.some((item:any)=>String(item.id)===requestedOrder)){setForm(current=>({...current,order_id:''}));setError('The selected request is not available in your account. Choose one of your requests below.') }}).catch(()=>setError('Your requests could not be loaded. You can still send a general support grievance.')).finally(()=>setLoadingOrders(false))},[requestedOrder])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setMsg('');setError('');setBusy(true);try{const payload:any={description:form.description};if(form.order_id)payload.order_id=Number(form.order_id);const r=await axios.post(`${apiBase}/grievances/`,payload,{headers:authHeader()});setMsg(r.data.message+(r.data.grievance?` Code: ${r.data.grievance.grievance_code}`:''));setForm({order_id:'',description:''})}catch(err:any){setError(err?.response?.data?.error||'We could not submit your grievance. Please try again.')}finally{setBusy(false)}}
 return <div className="form-page"><div className="form-hero"><span className="eyebrow">Support</span><h1>Get help with a request</h1><p>Tell us what went wrong or what you need from the service team.</p></div><div className="form-card"><form onSubmit={submit} className="request-form"><label>Related request (optional)<select value={form.order_id} onChange={e=>setForm({...form,order_id:e.target.value})} disabled={loadingOrders}><option value="">General support — not linked to a request</option>{orders.map(order=><option value={order.id} key={order.id}>{order.order_code} — {order.service}</option>)}</select></label>{loadingOrders&&<p className="auth-hint" role="status">Loading your requests…</p>}<label>Describe the issue<textarea value={form.description} required minLength={10} maxLength={4000} rows={7} onChange={e=>setForm({...form,description:e.target.value})}/></label><p className="auth-hint">Never include passwords, OTPs, PINs or banking login details.</p>{error&&<p className="info" role="alert">{String(error)}</p>}{msg&&<p className="success-message" role="status">{msg} <Link to="/grievances">Track your grievance</Link></p>}<button type="submit" disabled={busy}>{busy?'Submitting…':'Submit grievance'}</button></form></div><p className="form-back"><Link to="/grievances">← Back to grievances</Link></p></div>
}
