import React,{useEffect,useMemo,useState} from 'react'
import axios from 'axios'
import {Link,useLocation,useParams} from 'react-router-dom'
import Seo from '../components/ui/Seo'
import FeeSummary from '../components/ui/FeeSummary'
import {apiBase} from '../services/apiBase'
import {fetchClientProfile} from '../services/auth'
import {fetchJob,JobNotification} from '../services/jobs'
import {fetchScholarship,Scholarship} from '../services/scholarships'
import {getToken,getUser} from '../services/localStorage'
import {getSession} from '../services/session'
import {readCachedServices,slugifyServiceName} from '../services/serviceCatalog'

type Field={key:string;label:string;type?:'text'|'date'|'select';options?:string[];placeholder?:string}
type Profile={match:RegExp;fields:Field[];documents:string[]}
const TIMEOUT=12000,MAX_FILES=20,MAX_BYTES=10*1024*1024
const common:Field[]=[{key:'applicant_name',label:'Applicant name'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'father_or_guardian_name',label:'Father / mother / guardian name'},{key:'address',label:'Current address'},{key:'district',label:'District'},{key:'mandal_or_tehsil',label:'Mandal / Tahsil'}]
const fallback:Field[]=[...common,{key:'purpose_or_request',label:'Purpose / request details'},{key:'reference_number',label:'Existing application / ID / reference number'}]
const jobFields:Field[]=[{key:'job_post_preference',label:'Post / preference',placeholder:'Post, trade, cadre or preference'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'qualification',label:'Highest / relevant qualification',placeholder:'10th, Intermediate, Degree, Diploma, ITI, etc.'},{key:'qualification_board',label:'Board / university',placeholder:'Board or university name'},{key:'year_passed',label:'Year passed',placeholder:'Year of passing'},{key:'marks_or_cgpa',label:'Marks / percentage / CGPA',placeholder:'As shown on your certificate'},{key:'official_registration_number',label:'Existing OTR / registration number',placeholder:'Only if you already have one'},{key:'exam_region',label:'Exam centre / region / zone preference',placeholder:'If the recruitment asks for one'},{key:'experience',label:'Relevant experience',placeholder:'Employer, role and duration, if applicable'}]
const jobDocs=['Recent photograph','Signature image','Date-of-birth / 10th proof','Relevant qualification certificate or marks memo','Identity proof, if required by the official notice','Category / EWS / PwBD certificate, if applicable','Experience / NOC certificate, if applicable']
const scholarshipFields:Field[]=[{key:'student_name',label:'Student name'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'current_course',label:'Current course / class'},{key:'institution_name',label:'School / college / institution'},{key:'academic_year',label:'Academic year'},{key:'category',label:'Category / community'},{key:'family_income',label:'Annual family income'},{key:'previous_application_id',label:'Previous scholarship / application ID'}]
const scholarshipDocs=['Recent photograph','Student identity card / bonafide certificate','Latest marks memo / previous qualification certificate','Current admission / fee receipt, if available','Income certificate, if requested','Category / community / disability certificate, if applicable','Bank passbook first page / account proof, if requested','Aadhaar or other identity proof, only when requested']
const profiles:Profile[]=[
 {match:/income certificate/i,fields:[...common,{key:'occupation',label:'Occupation'},{key:'family_income',label:'Annual family income'},{key:'income_source',label:'Main source of income'},{key:'purpose',label:'Purpose for certificate'}],documents:['Aadhaar / identity proof','Address / residence proof','Ration card / family card, if available','Income proof / declaration','Land, pension or employment income proof, if applicable','Existing income certificate, if any']},
 {match:/caste|community|ews certificate/i,fields:[...common,{key:'community',label:'Community / caste'},{key:'sub_caste',label:'Sub-caste / group'},{key:'religion',label:'Religion'},{key:'existing_family_certificate',label:'Existing family community certificate number'},{key:'purpose',label:'Purpose for certificate'}],documents:['Aadhaar / identity proof','Address / residence proof','Birth / school record showing parent details','Parent / sibling caste or community certificate, if available','Ration card / family proof','Income / asset proof for EWS, if applicable']},
 {match:/residence|domicile|nativity/i,fields:[...common,{key:'years_at_address',label:'Years living at current address'},{key:'previous_address',label:'Previous address'},{key:'purpose',label:'Purpose for certificate'}],documents:['Aadhaar / identity proof','Current address proof','Ration card / voter ID / utility bill','School / study certificate, if relevant','Previous residence proof, if relevant']},
 {match:/birth certificate/i,fields:[{key:'child_name',label:'Name on birth record'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'place_of_birth',label:'Place of birth'},{key:'father_name',label:"Father's name"},{key:'mother_name',label:"Mother's name"},{key:'hospital_or_registration',label:'Hospital / registration details'},{key:'registration_number',label:'Birth registration number'}],documents:['Hospital birth record / discharge summary','Parent identity proofs','Birth acknowledgement / registration slip, if available','School record, if relevant','Supporting correction proof, if applicable']},
 {match:/death certificate/i,fields:[{key:'deceased_name',label:'Name of deceased'},{key:'date_of_death',label:'Date of death',type:'date'},{key:'place_of_death',label:'Place of death'},{key:'relative_name',label:'Father / spouse / relative name'},{key:'applicant_relation',label:'Your relation to the deceased'},{key:'registration_number',label:'Death registration number'}],documents:['Hospital / doctor death record, if available','Deceased identity proof','Applicant identity proof','Death acknowledgement / registration slip, if available','Burial / cremation record, if applicable']},
 {match:/marriage certificate/i,fields:[{key:'bride_name',label:'Bride name'},{key:'groom_name',label:'Groom name'},{key:'marriage_date',label:'Date of marriage',type:'date'},{key:'marriage_place',label:'Place of marriage'},{key:'bride_dob',label:'Bride date of birth',type:'date'},{key:'groom_dob',label:'Groom date of birth',type:'date'}],documents:['Bride identity / age proof','Groom identity / age proof','Address proofs','Marriage invitation / proof, if available','Marriage photographs, if requested','Witness identity proofs, if requested']},
 {match:/aadhaar/i,fields:[{key:'aadhaar_last_four',label:'Last 4 digits of Aadhaar'},{key:'request_type',label:'Update / correction requested'},{key:'current_name',label:'Current name on Aadhaar'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'address',label:'Address details'},{key:'registered_mobile',label:'Registered mobile number'}],documents:['Existing Aadhaar / e-Aadhaar','Proof supporting requested update','Address proof for address update','Date-of-birth proof for DOB-related requests','Name / relationship proof, if applicable']},
 {match:/pan card|pan application/i,fields:[{key:'applicant_name',label:'Applicant name'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'father_name',label:"Father's name"},{key:'pan_number',label:'Existing PAN number'},{key:'aadhaar_last_four',label:'Last 4 digits of Aadhaar'},{key:'request_type',label:'New PAN / correction / reprint'},{key:'address',label:'Communication address'}],documents:['Recent photograph, when requested','Signature image, when requested','Identity proof','Address proof','Date-of-birth proof','Existing PAN card, for correction / reprint']},
 {match:/passport/i,fields:[{key:'applicant_name',label:'Applicant name'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'place_of_birth',label:'Place of birth'},{key:'passport_number',label:'Existing passport number'},{key:'request_type',label:'Fresh / reissue / correction'},{key:'address',label:'Current address'}],documents:['Date-of-birth proof','Current address proof','Identity proof','Existing passport pages, for reissue','Name / marriage change proof, if applicable']},
 {match:/driving licence|learner.*licen/i,fields:[{key:'applicant_name',label:'Applicant name'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'licence_number',label:'Existing licence number'},{key:'vehicle_class',label:'Vehicle class'},{key:'request_type',label:'Learner / new / renewal / correction'},{key:'rto',label:'RTO / transport office'},{key:'address',label:'Current address'}],documents:['Recent photograph, if requested','Age / date-of-birth proof','Address proof','Existing driving licence, for renewal / correction','Learner licence, when relevant','Medical certificate, when requested']},
 {match:/land|pahani|adangal|1b|mutation|property/i,fields:[{key:'owner_name',label:'Owner / pattadar name'},{key:'survey_number',label:'Survey / sub-division number'},{key:'village',label:'Village'},{key:'mandal',label:'Mandal'},{key:'district',label:'District'},{key:'extent',label:'Land extent'},{key:'document_number',label:'Existing document / passbook number'}],documents:['Pattadar passbook / title document, if available','Registered sale / gift / inheritance document, if relevant','Existing pahani / adangal / 1B record','Owner identity proof','Survey / tax / property record, if available']},
 {match:/pension/i,fields:[{key:'beneficiary_name',label:'Beneficiary name'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'pension_type',label:'Pension type'},{key:'pension_id',label:'Existing pension / beneficiary ID'},{key:'bank_last_four',label:'Last 4 digits of bank account'},{key:'address',label:'Current address'}],documents:['Beneficiary identity proof','Age / date-of-birth proof','Address proof','Bank passbook first page / account proof','Income / eligibility proof, if requested','Existing pension record, if any']},
 {match:/scheme|welfare|benefit/i,fields:[{key:'beneficiary_name',label:'Beneficiary name'},{key:'date_of_birth',label:'Date of birth',type:'date'},{key:'category',label:'Category / community'},{key:'annual_income',label:'Annual family income'},{key:'occupation',label:'Occupation'},{key:'address',label:'Current address'},{key:'beneficiary_id',label:'Existing beneficiary / scheme ID'}],documents:['Beneficiary identity proof','Address proof','Income certificate, if requested','Category / community certificate, if applicable','Bank account proof, if DBT applies','Scheme-specific eligibility proof']},
 {match:/mobile.*recharge|postpaid/i,fields:[{key:'mobile_number',label:'Mobile number'},{key:'operator',label:'Operator'},{key:'circle',label:'Circle / state'},{key:'requested_amount_inr',label:'Preferred amount / plan'}],documents:['Recharge plan screenshot, if available','Latest postpaid bill, for postpaid payment','Previous recharge / payment receipt, if useful']},
 {match:/dth/i,fields:[{key:'subscriber_id',label:'Subscriber / customer ID'},{key:'provider',label:'DTH provider'},{key:'requested_amount_inr',label:'Preferred amount / plan'}],documents:['DTH account / plan screenshot','Latest DTH bill or recharge reminder','Previous recharge receipt, if useful']},
 {match:/fastag/i,fields:[{key:'vehicle_number',label:'Vehicle number'},{key:'registered_mobile',label:'Registered mobile number'},{key:'provider',label:'Issuer / bank'},{key:'requested_amount_inr',label:'Preferred amount'}],documents:['FASTag account / plan screenshot with sensitive data hidden','Vehicle registration certificate, only if needed','Previous FASTag recharge receipt, if useful']},
 {match:/electric|water|gas|broadband|landline|bill payment/i,fields:[{key:'consumer_number',label:'Consumer / account number'},{key:'provider',label:'Provider'},{key:'bill_month',label:'Bill month / billing period'},{key:'requested_amount_inr',label:'Bill amount'}],documents:['Latest bill / demand notice','Consumer or account page screenshot, if useful','Previous payment receipt, if useful']}
]
const uniq=<T,>(items:T[])=>items.filter((item,index)=>items.indexOf(item)===index)
function cachedService(id?:string,slug?:string){const n=slug?slugifyServiceName(slug):'';return readCachedServices(true).find((x:any)=>id?String(x.id)===String(id):n&&[x.slug,slugifyServiceName(x.name),slugifyServiceName(x.catalog_name||'')].filter(Boolean).includes(n))||null}
function profileFor(service:any){const text=[service?.name,service?.catalog_name,service?.category,service?.description,service?.keywords].filter(Boolean).join(' ');return profiles.find(p=>p.match.test(text))||null}

export default function UniversalServiceRequestV2(){
 const {id,slug}=useParams();const location=useLocation();const session=getSession();const localUser=getUser();const params=new URLSearchParams(location.search);const jobSlug=params.get('job')||'';const scholarshipSlug=params.get('scholarship')||''
 const initial=useMemo(()=>cachedService(id,slug),[id,slug]);const [service,setService]=useState<any>(initial);const [loading,setLoading]=useState(!initial);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [answers,setAnswers]=useState<Record<string,string>>({});const [notes,setNotes]=useState('');const [files,setFiles]=useState<File[]>([]);const [profile,setProfile]=useState<any>(localUser||null);const [job,setJob]=useState<JobNotification|null>(null);const [scholarship,setScholarship]=useState<Scholarship|null>(null);const [step,setStep]=useState<1|2|3>(1);const [order,setOrder]=useState<any>(null)
 useEffect(()=>{let active=true;if(initial){setService(initial);setLoading(false)}const endpoint=slug?`${apiBase}/services/by-slug/${encodeURIComponent(slug)}`:`${apiBase}/services/${id}`;axios.get(endpoint,{timeout:TIMEOUT}).then(r=>active&&setService(r.data)).catch(()=>{if(active&&!initial)setError('Unable to load this service right now.')}).finally(()=>active&&setLoading(false));return()=>{active=false}},[id,slug])
 useEffect(()=>{if(!session||session.is_admin)return;fetchClientProfile().then(r=>setProfile(r.user)).catch(()=>{})},[session?.user_id])
 useEffect(()=>{let active=true;if(!jobSlug){setJob(null);return()=>{active=false}}fetchJob(jobSlug).then(r=>active&&setJob(r.job)).catch(()=>active&&setError('The selected job notice is unavailable or has closed.'));return()=>{active=false}},[jobSlug])
 useEffect(()=>{let active=true;if(!scholarshipSlug){setScholarship(null);return()=>{active=false}}fetchScholarship(scholarshipSlug).then(r=>active&&setScholarship(r)).catch(()=>active&&setError('The selected scholarship is unavailable or has closed.'));return()=>{active=false}},[scholarshipSlug])
 const requirements=service?.requirements||{},selected=useMemo(()=>profileFor(service),[service?.id,service?.name,service?.category,service?.description])
 const fields=useMemo<Field[]>(()=>{const serviceFields:Field[]=(requirements.fields||[]).map((f:any)=>({key:String(f.key),label:String(f.label||f.key),type:f.type==='date'||f.type==='select'?f.type:'text',options:Array.isArray(f.options)?f.options:undefined,placeholder:f.placeholder}));const feeFields:Field[]=(job?.fee_factors||[]).map((f:any)=>({key:String(f.key),label:String(f.label),type:f.type==='select'||f.type==='boolean'?'select':'text',options:f.type==='boolean'?['Yes','No']:(f.options||[])}));const base=selected?.fields?.length?[...selected.fields,...serviceFields]:serviceFields.length?serviceFields:fallback;const all=scholarship?[...scholarshipFields,...base]:job?[...feeFields,...jobFields,...base]:base;return all.filter((f,i)=>all.findIndex(x=>x.key===f.key)===i)},[service?.id,selected,job?.id,scholarship?.id])
 const documents=useMemo(()=>uniq<string>([...(job?jobDocs:scholarship?scholarshipDocs:(selected?.documents||[])),...(requirements.documents||[])]),[service?.id,selected,job?.id,scholarship?.id])
 const title=scholarship?`Apply for ${scholarship.title}`:job?`Apply for ${job.title}`:service?.name||'Service request';const kind=job?'job':scholarship?'scholarship':/recharge|bill|dth|fastag|electric|water|gas|broadband|landline/i.test([service?.name,service?.category].join(' '))?'payment request':'service'
 const addFiles=(selectedFiles:File[])=>{const tooBig=selectedFiles.find(f=>f.size>MAX_BYTES);if(tooBig){setError(`${tooBig.name} is larger than 10 MB.`);return}setFiles(current=>{const existing=new Set(current.map(f=>`${f.name}:${f.size}:${f.lastModified}`));const additions=selectedFiles.filter(f=>!existing.has(`${f.name}:${f.size}:${f.lastModified}`));if(current.length+additions.length>MAX_FILES){setError(`You can upload a maximum of ${MAX_FILES} documents for one request.`);return current}setError('');return [...current,...additions]})}
 const review=()=>{if(!profile?.name||!profile?.phone){setError('Please complete your name and phone number in Account Settings before continuing.');return}setError('');setStep(2);window.scrollTo({top:0,behavior:'smooth'})}
 const submit=async()=>{setBusy(true);setError('');try{const application_data:any={service_name:service.name,request_mode:'guided',request_notes:notes.trim()};fields.forEach(f=>{const value=(answers[f.key]||'').trim();if(value)application_data[f.key]=value});if(job)Object.assign(application_data,{job_slug:job.slug,job_title:job.title,job_organization:job.organization,job_official_notice_url:job.official_notice_url,job_application_url:job.application_url,job_source:job.source?.name||null});if(scholarship)Object.assign(application_data,{scholarship_slug:scholarship.slug,scholarship_title:scholarship.title,scholarship_provider:scholarship.provider,scholarship_source:scholarship.source_name,scholarship_source_url:scholarship.source_url,scholarship_application_url:scholarship.application_url,no_official_fee:true});const response=await axios.post(`${apiBase}/orders/`,{service_id:Number(service.id),application_data},{headers:{Authorization:`Bearer ${getToken()}`},timeout:TIMEOUT});for(const file of files){const form=new FormData();form.append('file',file);form.append('order_id',String(response.data.order.id));await axios.post(`${apiBase}/uploads/`,form,{headers:{Authorization:`Bearer ${getToken()}`},timeout:30000})}setOrder(response.data.order);setStep(3);window.scrollTo({top:0,behavior:'smooth'})}catch(e:any){setError(e?.response?.data?.error||'Unable to submit this request. Please try again.')}finally{setBusy(false)}}
 if(loading)return <div className="jobs-loading" role="status"><div className="loading-dot"/><p>Loading application…</p></div>
 if(!service)return <div className="empty-dashboard"><h1>Service unavailable</h1><p>{error||'This service could not be found.'}</p><Link to="/government-services">Browse services</Link></div>
 const returnTo=encodeURIComponent(`${location.pathname}${location.search}`)
 if(!session)return <div className="service-detail-page"><Seo title={title} description={service.description||'Application assistance request'} path={location.pathname}/><section className="dashboard-section"><h1>{title}</h1><p>Sign in first. You will return here to enter relevant details, add relevant documents you have, review the request, submit it, and then continue to payment and tracking.</p><div className="cta-row"><Link className="btn btn-primary" to={`/login?returnTo=${returnTo}`}>Client login</Link><Link className="btn btn-secondary" to={`/register?returnTo=${returnTo}`}>Create account</Link></div></section></div>
 if(session.is_admin)return <div className="empty-dashboard"><h1>Client request page</h1><p>Use a client account to submit applications.</p><Link to="/admin/dashboard">Admin dashboard</Link></div>
 return <div className="service-detail-page"><Seo title={title} description={service.description||'Application assistance request'} path={location.pathname}/>
 {step===1&&<section className="dashboard-section request-form simplified-request-form"><h2>{job?'Job application details':scholarship?'Scholarship application details':kind==='payment request'?'Payment request details':'Application details'}</h2><div className="request-contact-summary"><div><strong>{profile?.name}</strong><span>{profile?.phone}{profile?.email?` · ${profile.email}`:''}</span></div><Link to="/account-settings">Edit profile</Link></div>{job&&<div className="info"><strong>Job:</strong> {job.title}<br/><strong>Organization:</strong> {job.organization}</div>}{scholarship&&<div className="info"><strong>Scholarship:</strong> {scholarship.title}<br/><strong>Provider:</strong> {scholarship.provider}</div>}<FeeSummary data={service}/><h3>{job?'Job Application Details':scholarship?'Scholarship Application Details':kind==='payment request'?'Request Details':'Application Details'}</h3><p className="request-short-hint">Add any details you know to help the admin process your request faster.</p>{fields.map(f=><label key={f.key}>{f.label}{f.type==='select'?<select value={answers[f.key]||''} onChange={e=>setAnswers(a=>({...a,[f.key]:e.target.value}))}><option value="">Select</option>{(f.options||[]).map(o=><option key={o} value={o}>{o}</option>)}</select>:<input type={f.type||'text'} value={answers[f.key]||''} placeholder={f.placeholder||''} onChange={e=>setAnswers(a=>({...a,[f.key]:e.target.value}))}/>}</label>)}<label>Short note<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Short note, if needed"/></label><div className="upload-card"><h3>Documents relevant to this {kind}</h3>{documents.length?<ul>{documents.map(d=><li key={d}>{d}</li>)}</ul>:<p>Upload any document that helps the admin process this request.</p>}<p>Upload only documents that apply to you. You can submit now without them and add them later if the admin asks.</p><label>Upload documents (multiple)<input type="file" multiple accept=".pdf,.png,.jpg,.jpeg" onChange={e=>{addFiles(Array.from(e.target.files||[]));e.currentTarget.value=''}}/></label><p>Add files once or in several selections · PDF, PNG or JPG · maximum 20 files · maximum 10 MB each.</p>{files.length>0&&<ul>{files.map((file,index)=><li key={`${file.name}:${file.lastModified}`}>{file.name} <button className="btn btn-link" type="button" onClick={()=>setFiles(current=>current.filter((_,i)=>i!==index))}>Remove</button></li>)}</ul>}</div><p className="request-safety-line">Do not enter OTPs, passwords, PINs or banking details. You will authorize those steps yourself on the official portal.</p>{error&&<p className="info" role="alert">{error}</p>}<button className="btn btn-primary" type="button" onClick={review}>Review request</button></section>}
 {step===2&&<section className="dashboard-section request-form simplified-request-form"><span className="eyebrow">Review request</span><h2>Review before submitting</h2><div className="request-contact-summary"><div><strong>{profile?.name}</strong><span>{profile?.phone}{profile?.email?` · ${profile.email}`:''}</span></div><button className="btn btn-link" type="button" onClick={()=>setStep(1)}>Edit details</button></div><div className="payment-review-grid"><div><span>Service</span><strong>{title}</strong></div>{fields.filter(f=>(answers[f.key]||'').trim()).map(f=><div key={f.key}><span>{f.label}</span><strong>{answers[f.key]}</strong></div>)}{notes.trim()&&<div><span>Short note</span><strong>{notes}</strong></div>}<div><span>Documents selected</span><strong>{files.length}</strong></div></div><FeeSummary data={service}/><p className="request-short-hint">You can submit even if some details or documents are not available. The administrator can confirm anything missing with you.</p>{error&&<p className="info" role="alert">{error}</p>}<div className="cta-row"><button className="btn btn-secondary" type="button" onClick={()=>setStep(1)}>← Edit details</button><button className="btn btn-primary" type="button" disabled={busy} onClick={submit}>{busy?'Submitting…':'Submit application'}</button></div></section>}
 {step===3&&order&&<section className="dashboard-section request-form simplified-request-form"><span className="eyebrow">Request submitted</span><h2>Application submitted</h2><p>Your reference number is <strong>{order.order_code||order.id}</strong>.</p><p>Continue to the request page for applicable fee payment, status tracking, editing details and adding any remaining documents.</p><div className="cta-row"><Link className="btn btn-primary" to={`/my-orders/${order.id}`}>Continue to payment & tracking</Link><Link className="btn btn-secondary" to="/my-orders">My applications</Link></div></section>}
 </div>
}
