import React,{lazy,Suspense} from 'react'
import {Routes,Route,Navigate,useLocation} from 'react-router-dom'
import Home from './pages/Home'
import NavBar from './components/ui/NavBar'
import Footer from './components/ui/Footer'
import {getSession} from './services/session'
import SupportChatLauncher from './components/ui/SupportChatLauncher'
import Seo,{SITE} from './components/ui/Seo'

const ServiceDetail=lazy(()=>import('./pages/ServiceDetail')),Login=lazy(()=>import('./pages/Login')),AdminLogin=lazy(()=>import('./components/admin/AdminLogin')),AdminPanel=lazy(()=>import('./components/admin/AdminPanel')),Register=lazy(()=>import('./pages/Register')),MyOrders=lazy(()=>import('./pages/MyOrders')),OrderDetail=lazy(()=>import('./pages/OrderDetail')),AccountSettings=lazy(()=>import('./pages/AccountSettings')),RequestReset=lazy(()=>import('./pages/RequestReset')),ResetPassword=lazy(()=>import('./pages/ResetPassword')),Category=lazy(()=>import('./pages/Category')),SubmitGrievance=lazy(()=>import('./pages/SubmitGrievance')),MyGrievances=lazy(()=>import('./pages/MyGrievances')),SubmitReview=lazy(()=>import('./pages/SubmitReview')),About=lazy(()=>import('./pages/About')),Contact=lazy(()=>import('./pages/Contact')),PrivacyPolicy=lazy(()=>import('./pages/PrivacyPolicy')),Terms=lazy(()=>import('./pages/Terms')),Disclaimer=lazy(()=>import('./pages/Disclaimer')),NotFound=lazy(()=>import('./pages/NotFound')),SupportMessages=lazy(()=>import('./pages/SupportMessages')),Jobs=lazy(()=>import('./pages/Jobs')),JobDetail=lazy(()=>import('./pages/JobDetail')),Scholarships=lazy(()=>import('./pages/Scholarships')),ScholarshipDetail=lazy(()=>import('./pages/ScholarshipDetail'))
const PUBLIC_METADATA:Record<string,{title:string;description:string}>={
 '/':{title:'Public Online Service Provider — Application Assistance',description:'Find independent assistance for PAN cards, certificates, government jobs, scholarships, schemes, MeeSeva and other public-service applications.'},'/jobs':{title:'Government Jobs & Recruitment Notices',description:'Review current government and private recruitment notices gathered from approved official sources, with deadlines and important details where available.'},'/scholarships':{title:'Scholarships & Application Assistance',description:'Search active scholarships, check eligibility and get independent application assistance.'},'/meeseva':{title:'MeeSeva and Online Public Service Assistance',description:'Find independent assistance for eligible MeeSeva and other online public-service applications.'},'/certificates':{title:'Government Certificate Application Assistance',description:'Explore help with eligible income, caste, residence, birth, death and other certificate applications.'},'/schemes':{title:'Government Scheme Application Assistance',description:'Explore independent eligibility and application assistance for government schemes and welfare services.'},'/about':{title:'About Public Online Service Provider',description:'Learn how Public Online Service Provider offers private, independent assistance for public-service applications.'},'/contact':{title:'Contact Public Online Service Provider',description:'Contact Public Online Service Provider for help choosing an available public-service assistance option.'},'/privacy':{title:'Privacy Policy',description:'Read how Public Online Service Provider handles account, request and service information.'},'/terms':{title:'Terms and Conditions',description:'Read the terms that apply when using Public Online Service Provider.'},'/disclaimer':{title:'Independent Provider Disclaimer',description:'Public Online Service Provider is an independent private assistance platform, not a government department or official portal.'}}
function RouteMetadata(){const location=useLocation(),path=location.pathname.replace(/\/$/,'')||'/';if(path.startsWith('/services/')||path.startsWith('/service/')||path.startsWith('/jobs/')||path.startsWith('/scholarships/'))return null;const metadata=PUBLIC_METADATA[path],index=Boolean(metadata),schema=path==='/'?[{'@context':'https://schema.org','@type':'WebSite',name:SITE.name,url:SITE.url,description:SITE.description,inLanguage:'en-IN'},{'@context':'https://schema.org','@type':'Organization',name:SITE.name,url:SITE.url,description:'Independent private assistance provider for public-service applications.'}]:metadata?{'@context':'https://schema.org','@type':'WebPage',name:metadata.title,url:`${SITE.url}${path}`,description:metadata.description,isPartOf:{'@type':'WebSite',name:SITE.name,url:SITE.url}}:undefined;return <Seo title={metadata?.title||'Private account page'} description={metadata?.description||'Private account or authentication page for Public Online Service Provider.'} path={path} index={index} schema={schema}/>}
function safeReturnTo(value:string|null){if(!value)return null;try{const decoded=decodeURIComponent(value);return decoded.startsWith('/')&&!decoded.startsWith('//')&&!decoded.startsWith('/login')&&!decoded.startsWith('/register')&&!decoded.startsWith('/admin/login')?decoded:null}catch{return null}}
function AuthRedirect({children}:{children:React.ReactNode}){const location=useLocation(),session=getSession();if(!session)return <>{children}</>;const returnTo=safeReturnTo(new URLSearchParams(location.search).get('returnTo'));if(returnTo)return <Navigate to={returnTo} replace/>;return <Navigate to={session.is_admin?'/admin/dashboard':'/my-orders'} replace/>}
function ClientRoute({children}:{children:React.ReactNode}){const session=getSession(),location=useLocation();if(!session){const returnTo=encodeURIComponent(`${location.pathname}${location.search}${location.hash}`);return <Navigate to={`/login?returnTo=${returnTo}`} replace/>}if(session.is_admin)return <Navigate to="/admin/dashboard" replace/>;return <>{children}</>}
function AdminRoute({children}:{children:React.ReactNode}){const session=getSession(),location=useLocation();if(!session){const returnTo=encodeURIComponent(`${location.pathname}${location.search}${location.hash}`);return <Navigate to={`/admin/login?returnTo=${returnTo}`} replace/>}if(!session.is_admin)return <Navigate to="/my-orders" replace/>;return <>{children}</>}
const Loader=()=> <div className="jobs-loading" role="status"><div className="loading-dot"/><p>Loading…</p></div>
export default function App(){return <div className="app-shell"><RouteMetadata/><a className="skip-link" href="#main-content">Skip to main content</a><NavBar/><main id="main-content" tabIndex={-1} className="container page-content"><Suspense fallback={<Loader/>}><Routes>
<Route path="/" element={<Home/>}/><Route path="/services/:slug" element={<ServiceDetail/>}/><Route path="/service/:id" element={<ServiceDetail/>}/><Route path="/jobs" element={<Jobs/>}/><Route path="/jobs/:slug" element={<JobDetail/>}/><Route path="/scholarships" element={<Scholarships/>}/><Route path="/scholarships/:slug" element={<ScholarshipDetail/>}/><Route path="/meeseva" element={<Category/>}/><Route path="/certificates" element={<Category/>}/><Route path="/schemes" element={<Category/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy" element={<PrivacyPolicy/>}/><Route path="/terms" element={<Terms/>}/><Route path="/disclaimer" element={<Disclaimer/>}/>
<Route path="/login" element={<AuthRedirect><Login/></AuthRedirect>}/><Route path="/register" element={<AuthRedirect><Register/></AuthRedirect>}/><Route path="/admin/login" element={<AuthRedirect><AdminLogin/></AuthRedirect>}/><Route path="/request-reset" element={<RequestReset/>}/><Route path="/admin/request-reset" element={<RequestReset accountType="admin"/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/my-orders" element={<ClientRoute><MyOrders/></ClientRoute>}/><Route path="/my-orders/:id" element={<ClientRoute><OrderDetail/></ClientRoute>}/><Route path="/account-settings" element={<ClientRoute><AccountSettings/></ClientRoute>}/><Route path="/messages" element={<ClientRoute><SupportMessages/></ClientRoute>}/><Route path="/grievances" element={<ClientRoute><MyGrievances/></ClientRoute>}/><Route path="/submit-grievance" element={<ClientRoute><SubmitGrievance/></ClientRoute>}/><Route path="/submit-review" element={<ClientRoute><SubmitReview/></ClientRoute>}/><Route path="/admin/*" element={<AdminRoute><AdminPanel/></AdminRoute>}/><Route path="*" element={<NotFound/>}/>
</Routes></Suspense></main><SupportChatLauncher/><Footer/></div>}
